### ISSUE TITLE
Incompatibility with pyvista 0.41.0

### ISSUE THREAD

**Issue by jonathanzopes** [ansys/pydpf-core#1058]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The most recent pyvista release 0.41 removed the deprecated `rcParams` dictionary. 

When using `pyvista-0.41.1` with `ansys-dpf-core-0.8.1`, we see the following failure to import dpf core.

![image](https://github.com/ansys/pydpf-core/assets/65216347/9d0bf334-6f60-46cf-8c2d-48545a92c45e)

### Steps To Reproduce

In a virtual env install ansys-dpf-core 0.8.1 and pyvista 0.41 and run `import ansys.dpf.core as dpf`.

### Which Operating System causes the issue?

Linux

### Which DPF/Ansys version are you using?

Ansys 2023 R2

### Which Python version causes the issue?

3.8

### Installed packages

pyvista==0.41.1
ansys-dpf-core==0.8.1

**Comment by PProfizi** [comment]
Hi @jonathanzopes! Thank you for raising this issue!
Indeed we noticed end of last week and a fix has been made and merged in our master branch.
A release of ansys-dpf-core 0.9.0 is planned for before the end of this week.
In the meantime you can `pip uninstall -y pyvista; pip install pyvista==0.40.0` to not have this issue with ansys-dpf-core 0.8.1.

**Comment by jonathanzopes** [comment]
Hi @PProfizi, 

Thanks - yes we fixed our env by pinning pyvista to 0.40.0 as you suggested.
