### ISSUE TITLE
DPFServerException

### ISSUE THREAD

**Issue by KDdot807** [ansys/pydpf-core#1087]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I have just installed the ansys-dpf-core in a python virtual environment (3.10.11). When I try to launch the brief demo it retrieves an error. (File attached)
![Capture_ANSYSDPFERROR](https://github.com/ansys/pydpf-core/assets/126331959/3865e77d-9ada-41be-8195-d45d7db58fb1)

### Steps To Reproduce

Given the ANSYS Student 2023 R2 and the ansys-mapdl-core and ansys-dpf-core installed in a python virtual  environment created in python3.10.11 (upgrade pip). Maybe I missing some envirionment variables I don't know. I have read in some othe other posts that there is a environment variable that I need to set manually so the DPFserver can run. I can't find the post, and I don't remember the name exactly but I remember the value that it must have 'Y' like saying yes to something.

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2023 R2

### Which Python version causes the issue?

3.10

### Installed packages

ansys-api-mapdl                       0.5.1
ansys-api-platform-instancemanagement 1.0.0b3
ansys-dpf-core                        0.8.1
ansys-dpf-gate                        0.3.1
ansys-dpf-gatebin                     0.3.1
ansys-grpc-dpf                        0.7.1
ansys-mapdl-core                      0.65.1
ansys-mapdl-reader                    0.52.20
ansys-platform-instancemanagement     1.1.1
ansys-tools-path                      0.3.1
appdirs                               1.4.4
cachetools                            5.3.1
certifi                               2023.7.22
charset-normalizer                    3.2.0
click                                 8.1.6
colorama                              0.4.6
contourpy                             1.1.0
cycler                                0.11.0
fonttools                             4.41.1
geomdl                                5.3.1
google-api-core                       2.11.1
google-api-python-client              2.95.0
google-auth                           2.22.0
google-auth-httplib2                  0.1.0
googleapis-common-protos              1.60.0
grpcio                                1.56.2
httplib2                              0.22.0
idna                                  3.4
importlib-metadata                    6.8.0
kiwisolver                            1.4.4
matplotlib                            3.7.2
numpy                                 1.25.2
packaging                             23.1
Pillow                                10.0.0
pip                                   23.2.1
platformdirs                          3.10.0
pooch                                 1.7.0
protobuf                              3.20.3
protoc-gen-swagger                    0.1.0
psutil                                5.9.5
pyansys-tools-versioning              0.4.0
pyasn1                                0.5.0
pyasn1-modules                        0.3.0
pyiges                                0.3.1
pyparsing                             3.0.9
python-dateutil                       2.8.2
pyvista                               0.40.4
requests                              2.31.0
rsa                                   4.9
scipy                                 1.11.1
scooby                                0.7.2
setuptools                            65.5.0
six                                   1.16.0
tqdm                                  4.65.0
uritemplate                           4.1.1
urllib3                               1.26.16
vtk                                   9.2.6
zipp                                  3.16.2

**Comment by PProfizi** [comment]
Hello @KDdot807,
The `ANSYS_DPF_ACCEPT_LA=Y` environment variable is indeed required when using DPF Server, for which you can find all the necessary information (including how to download it) here https://dpf.docs.pyansys.com/version/stable/user_guide/getting_started_with_dpf_server.html.
DPF should however be available in your Ansys 2023R2 installation, and your Python venv seems correct.
What I would suggest is to print the path to the file it is trying to read as the error indicates an issue when trying to read the file:
`print(examples.find_simple_bar())`
You can then verify that this path is correct.

**Comment by KDdot807** [comment]
Hi @PProfizi , thanks for the quick response. 

I have done what you suggested and the path seems to be correct.
![Capture_ANSYSDPFERROR3](https://github.com/ansys/pydpf-core/assets/126331959/501715fc-10d0-4708-915c-e921ddbab8e6)

 I also loaded the .rst in MAPDL and in reads/loads
 fine.
![Capture_ANSYSDPFERROR2](https://github.com/ansys/pydpf-core/assets/126331959/ee2229a0-f427-4ff1-9217-04ded86edd61)



 So, I don't know what I need to look up exactly. Thanks in advanced.

**Comment by KDdot807** [comment]
Hi again, @PProfizi, and thanks for your patience. I know you are a very busy person. I would like to close this issue with the solution to the problem. It was a pretty basic error, and I hope it will be helpful for low-experience developers. Since I was running the commands directly in the Python interpreter, each statement was executed separately and immediately. Hence, there is no relation among the statements. To fix it you need to create a Script with the statements you want to use or use Jupyter notebook or run IPython like so:
![image](https://github.com/ansys/pydpf-core/assets/126331959/a6851d49-a84f-4be9-a280-dd9f783cb8dc)

**Comment by junming1202** [comment]
Hi KDdot807, I believe i encountered similar issue as you did. 
From your solution, it seems like you can only run PyDpf in ipython environment. 
Do you still face the same issue when running it in normal python envionment?

Here is also a DpfServerException issue i just opened:
https://github.com/ansys/pydpf-core/issues/1104

**Comment by KDdot807** [comment]
Hi @junming1202, it happens that I might need to re-open this issue. Yesterday I tried so many things to make it work that frankly I'm not sure what made it worked. Early today, I tried to run the examples and load other .rst and I have encountered the same problem again. So, what comes to my mind ( since I don't remember the sequence of commands I run yesterday) that I shutdown all dpf server sessions and start a new DPF server locally. Also I created a data source object and gave the paths of my .rst files to the attributes, so far this still does not work. May I ask, what have you done so far to make it work ?

**Comment by PProfizi** [comment]
Hi @KDdot807,
I think I will indeed reopen the issue as the example should still have worked even if run line by line in your Python console with the venv activated.
The PyDPF libraries are CPython and should not require an IPython console.
Can you maybe describe a bit more the context in which you are using DPF?

I gathered you are on a Windows machine, you have Ansys 2023 R2 installed and have an Education license available.
You created a Python 3.10 venv where you installed the libraries listed in the issue description, activated it and tried to run the first example line by line. Is that right?

**Comment by KDdot807** [comment]
Hi @PProfizi , that is correct. I also tried other things yesterday that I quite don't remember the sequence of commands that I ran. I remember to shutdown all dpf server sessions, and create a new one with:

`from ansys.dpf import core as dpf
server = dpf.start_local_server()`

At that time it didn't work. Then I tried: 
`from ansys.dpf import core as dpf
from ansys.dpf.core import examples
data_sources = dpf.DataSources()
data_sources.set_result_file_path(examples.download_crankshaft())
model = dpf.Model(examples.download_crankshaft())
print(model)`

also didn't work. After many attempts playing around with the functions on core.py, server.py all and running IPython it started working. After I closed the terminal, it started giving the same error all over again. I have just run the commands you posted line by line in the terminal and it gives this:

![image](https://github.com/ansys/pydpf-core/assets/126331959/b7a3b52e-f0aa-4577-a4e9-7894938a6775)

**Comment by junming1202** [comment]
Hi @KDdot807, I am still facing the issue currently as well. So also looking for solution as you are right now. For me, I started to encounter the DpFServer Exception issue after installing ANSYS 2023 R2. I still have my ANSYS 2022 R1 installed in the system. 

This is the issue that i created:
https://github.com/ansys/pydpf-core/issues/1104

**Comment by junming1202** [comment]
Hi @KDdot807 , I managed to got it work by uninstalling and reinstalling both python and ANSYS2023 R2 in my system.
Still not sure what causes the issue.
Please let me know if this works for you.

https://github.com/ansys/pydpf-core/issues/1104#issuecomment-1666445805

**Comment by KDdot807** [comment]
Hi @junming1202 , well I tried it but didn't work. So, what comes to my mind when you say to reinstall python is, are you using python virtual environments? or are you installing all you packages and python in the AppData folder in your user session of windows?

**Comment by junming1202** [comment]
Hi @KDdot807, yeah I am using the python virtual environment. So by uninstalling python, all packages are removed. When installing back the python, I reinstall all the packages

**Comment by KDdot807** [comment]
Hello @junming1202 @PProfizi I managed to make it work. I followed the recommendation of @junming1202 to reinstall everything. When uninstalling I made sure to delete all related folders of old ANSYS installation folders, and I noticed that I have the 2023R1 student version left the default folders, I also deleted some folders in the %APPDATA% path. Afterwards, I reinstalled the ANSYS 2023R2 Student version. And, when it comes to installing the pyansys libraries I took a different approach. I used the default python package located at :

```ruby
C:\Program Files\ANSYS Inc\ANSYS Student\v232\commonfiles\CPython\3_10\winx64\Release\python
```

Also make sure that this folder and Scripts folder are in the path environment variable of your user account like so:

![image](https://github.com/ansys/pydpf-core/assets/126331959/3538279a-e305-45a6-8729-2ce3a9e82b5f)


Now when creating the python environment create it in a folder when you are sure that you have all the permission necessary to write/read like so:

Open a command prompt:

``` ruby
"C:\Program Files\ANSYS Inc\ANSYS Student\v232\commonfiles\CPython\3_10\winx64\Release\python\python.exe" -m venv "%APPDATA%\MyEnv1"
```

Keep in mind that the %APPDATA% is C:\Users\<username>\AppData\Roaming folder on your Windows machine.

Now, activate the virtual environment:

```ruby
call "%APPDATA%\MyEnv1\Scripts\activate"
```
After activating the environment you can start installing all the libraries of pyansys you want/allow to work with, but first you need to upgrade pip like so:

```ruby
"%APPDATA%\MyEnv1\Scripts\python.exe" -m pip install --upgrade pip
```
Now you can install you preferred libraries of PyAnsys, like so:
```ruby
"%APPDATA%\MyEnv1\Scripts\pip" install ansys-mapdl-core
"%APPDATA%\MyEnv1\Scripts\pip" install ansys-mapdl-reader
"%APPDATA%\MyEnv1\Scripts\pip" install ansys-dpf-core
```

I could use the python interpreter of my python virtual environment (MyEnv1) as a kernel for Jupyter notebooks to be used in VSCode. This way I have found no problems so far. You can even use the python interpreter of your python virtual environment directly, IPython, Jupyter, or as I like better coding in VSCode as a script or Jupyter notebook.
