### ISSUE TITLE
problem running model.metadata.meshed_region 

### ISSUE THREAD

**Issue by mcMunich** [ansys/pydpf-core#1129]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

This is likely a spyder specific bug. If I try to run spyder in my virtual environment I get the error below when I try to get the metadata but the same error occurs for other lines of code. 

mesh_set2 = model.metadata.meshed_region
Traceback (most recent call last):

  Cell In[1], line 13
    mesh_set2 = model.metadata.meshed_region

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\model.py:106 in metadata
    self._metadata = Metadata(self._data_sources, self._server)

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\model.py:268 in __init__
    self._set_data_sources(data_sources)

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\model.py:416 in _set_data_sources
    self._cache_streams_provider()

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\model.py:298 in _cache_streams_provider
    self._stream_provider = Operator("stream_provider", server=self._server)

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\dpf_operator.py:129 in __init__
    if len(self._spec.inputs) > 0 and self._inputs is None:

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\operator_specification.py:341 in inputs
    self._fill_pins(True, self._map_input_pin_spec)

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\core\operator_specification.py:390 in _fill_pins
    self._api.operator_specification_get_pin_derived_class_type_name(

  File C:\spyderEnv\Lib\site-packages\ansys\dpf\gate\generated\operator_specification_capi.py:288 in operator_specification_get_pin_derived_class_type_name
    res = capi.dll.Operator_specification_GetPinDerivedClassTypeName(specification._internal_obj if specification is not None else None, binput, utils.to_int32(numPin), ctypes.byref(utils.to_int32(errorSize)), ctypes.byref(sError))

  File ~\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py:389 in __getattr__
    func = self.__getitem__(name)

  File ~\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py:394 in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

AttributeError: function 'Operator_specification_GetPinDerivedClassTypeName' not found

### Steps To Reproduce

Please see text below. 

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.11

### Installed packages

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\spyderEnv\Scripts\pip.exe\__main__.py", line 2, in <module>
  File "C:\Program Files\ANSYS Inc\v241\commonfiles\CPython\3_10\winx64\Release\python\Lib\re.py", line 125, in <module>
    import sre_compile
  File "C:\Program Files\ANSYS Inc\v241\commonfiles\CPython\3_10\winx64\Release\python\Lib\sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch

(This is a spyder issue). If I go to the venv:  
C:\spyderEnv\Scripts>python -m pip list
Package                               Version
------------------------------------- --------
aiohttp                               3.8.4
aiosignal                             1.3.1
alabaster                             0.7.13
ansi2html                             1.8.0
ansys-api-mapdl                       0.5.1
ansys-api-mechanical                  0.1.0
ansys-api-meshing-prime               0.1.1
ansys-api-platform-instancemanagement 1.0.0b3
ansys-dpf-core                        0.9.0
ansys-dpf-gate                        0.4.1
ansys-dpf-gatebin                     0.3.1
ansys-dpf-post                        0.5.0
ansys-grpc-dpf                        0.7.1
ansys-mapdl-core                      0.65.2
ansys-mapdl-reader                    0.52.20
ansys-mechanical-core                 0.10.1
ansys-meshing-prime                   0.4.0
ansys-platform-instancemanagement     1.1.1
ansys-pythonnet                       3.1.0rc1
ansys-tools-path                      0.3.1
anyio                                 3.7.1
appdirs                               1.4.4
argon2-cffi                           21.3.0
argon2-cffi-bindings                  21.2.0
arrow                                 1.2.3
astroid                               2.15.6
asttokens                             2.2.1
async-lru                             2.0.4
async-timeout                         4.0.2
atomicwrites                          1.4.1
attrs                                 23.1.0
autopep8                              2.0.2
Babel                                 2.12.1
backcall                              0.2.0
bcrypt                                4.0.1
beautifulsoup4                        4.12.2
binaryornot                           0.4.4
black                                 23.7.0
bleach                                6.0.0
cachetools                            5.3.1
certifi                               2023.5.7
cffi                                  1.15.1
chardet                               5.1.0
charset-normalizer                    3.2.0
click                                 8.1.4
cloudpickle                           2.2.1
clr-loader                            0.2.6
colorama                              0.4.6
comm                                  0.1.3
contourpy                             1.1.0
cookiecutter                          2.2.3
cryptography                          41.0.2
cycler                                0.11.0
dash                                  2.13.0
dash-core-components                  2.0.0
dash-html-components                  2.0.0
dash-table                            5.0.0
debugpy                               1.6.7
decorator                             5.1.1
defusedxml                            0.7.1
diff-match-patch                      20230430
dill                                  0.3.6
docstring-to-markdown                 0.12
docutils                              0.20.1
executing                             1.2.0
fastjsonschema                        2.17.1
flake8                                6.0.0
Flask                                 2.2.5
fonttools                             4.41.0
fqdn                                  1.5.1
frozenlist                            1.4.0
geomdl                                5.3.1
google-api-core                       2.11.1
google-api-python-client              2.93.0
google-auth                           2.22.0
google-auth-httplib2                  0.1.0
googleapis-common-protos              1.59.1
grpcio                                1.56.0
httplib2                              0.22.0
idna                                  3.4
imagesize                             1.4.1
importlib-metadata                    6.8.0
inflection                            0.5.1
intervaltree                          3.1.0
ipykernel                             6.24.0
ipython                               8.14.0
ipython-genutils                      0.2.0
ipywidgets                            8.0.7
isoduration                           20.11.0
isort                                 5.12.0
itsdangerous                          2.1.2
jaraco.classes                        3.3.0
jedi                                  0.18.2
jellyfish                             1.0.0
Jinja2                                3.1.2
json5                                 0.9.14
jsonpointer                           2.4
jsonschema                            4.18.2
jsonschema-specifications             2023.6.1
jupyter_client                        8.3.0
jupyter_core                          5.3.1
jupyter-events                        0.7.0
jupyter-lsp                           2.2.0
jupyter_server                        2.7.0
jupyter_server_terminals              0.4.4
jupyterlab                            4.0.3
jupyterlab-pygments                   0.2.2
jupyterlab_server                     2.24.0
jupyterlab-widgets                    3.0.8
keyring                               24.2.0
kiwisolver                            1.4.4
lazy-object-proxy                     1.9.0
MarkupSafe                            2.1.3
matplotlib                            3.7.2
matplotlib-inline                     0.1.6
mccabe                                0.7.0
mistune                               3.0.1
more-itertools                        9.1.0
multidict                             6.0.4
mypy-extensions                       1.0.0
nbclient                              0.8.0
nbconvert                             7.6.0
nbformat                              5.9.1
nest-asyncio                          1.5.6
notebook_shim                         0.2.3
numpy                                 1.25.1
numpydoc                              1.5.0
overrides                             7.3.1
packaging                             23.1
pandocfilters                         1.5.0
paramiko                              3.2.0
parso                                 0.8.3
pathspec                              0.11.1
pexpect                               4.8.0
pickleshare                           0.7.5
Pillow                                10.0.0
pip                                   23.2.1
platformdirs                          3.8.1
plotly                                5.15.0
pluggy                                1.2.0
pooch                                 1.7.0
prometheus-client                     0.17.1
prompt-toolkit                        3.0.39
protobuf                              3.20.3
protoc-gen-swagger                    0.1.0
psutil                                5.9.5
ptyprocess                            0.7.0
pure-eval                             0.2.2
pyansys-tools-versioning              0.4.0
pyasn1                                0.5.0
pyasn1-modules                        0.3.0
pycodestyle                           2.10.0
pycparser                             2.21
pydocstyle                            6.3.0
pyflakes                              3.0.1
Pygments                              2.15.1
pyiges                                0.3.1
pylint                                2.17.4
pylint-venv                           3.0.2
pyls-spyder                           0.4.0
PyNaCl                                1.5.0
pyparsing                             3.0.9
PyQt5                                 5.15.9
PyQt5-Qt5                             5.15.2
PyQt5-sip                             12.12.1
PyQtWebEngine                         5.15.6
PyQtWebEngine-Qt5                     5.15.2
python-dateutil                       2.8.2
python-json-logger                    2.0.7
python-lsp-black                      1.3.0
python-lsp-jsonrpc                    1.0.0
python-lsp-server                     1.7.4
python-slugify                        8.0.1
pytoolconfig                          1.2.5
pyvista                               0.40.1
pywin32                               306
pywin32-ctypes                        0.2.2
pywinpty                              2.0.11
PyYAML                                6.0
pyzmq                                 25.1.0
QDarkStyle                            3.1
qstylizer                             0.2.2
QtAwesome                             1.2.3
qtconsole                             5.4.3
QtPy                                  2.3.1
referencing                           0.29.1
requests                              2.31.0
retrying                              1.3.4
rfc3339-validator                     0.1.4
rfc3986-validator                     0.1.1
rope                                  1.9.0
rpds-py                               0.8.10
rsa                                   4.9
Rtree                                 1.0.1
scipy                                 1.11.1
scooby                                0.7.2
Send2Trash                            1.8.2
setuptools                            65.5.0
six                                   1.16.0
sniffio                               1.3.0
snowballstemmer                       2.2.0
sortedcontainers                      2.4.0
soupsieve                             2.4.1
Sphinx                                7.0.1
sphinxcontrib-applehelp               1.0.4
sphinxcontrib-devhelp                 1.0.2
sphinxcontrib-htmlhelp                2.0.1
sphinxcontrib-jsmath                  1.0.1
sphinxcontrib-qthelp                  1.0.3
sphinxcontrib-serializinghtml         1.1.5
spyder                                5.4.5
spyder-kernels                        2.4.4
stack-data                            0.6.2
tenacity                              8.2.2
terminado                             0.17.1
text-unidecode                        1.3
textdistance                          4.5.0
three-merge                           0.1.1
tinycss2                              1.2.1
tomli                                 2.0.1
tomlkit                               0.11.8
tornado                               6.3.2
tqdm                                  4.65.0
traitlets                             5.9.0
trame                                 3.2.4
trame-client                          2.10.0
trame-components                      2.1.1
trame-deckgl                          2.0.2
trame-markdown                        2.0.2
trame-matplotlib                      2.0.2
trame-plotly                          2.1.1
trame-rca                             0.3.1
trame-router                          2.0.2
trame-server                          2.11.7
trame-simput                          2.3.2
trame-vega                            2.0.3
trame-vtk                             2.5.4
trame-vuetify                         2.2.4
typing_extensions                     4.7.1
ujson                                 5.8.0
uri-template                          1.3.0
uritemplate                           4.1.1
urllib3                               1.26.16
vtk                                   9.2.6
watchdog                              3.0.0
wcwidth                               0.2.6
webcolors                             1.13
webencodings                          0.5.1
websocket-client                      1.6.1
Werkzeug                              2.2.3
whatthepatch                          1.0.5
widgetsnbextension                    4.0.8
wrapt                                 1.15.0
wslink                                1.11.1
yapf                                  0.40.1
yarl                                  1.9.2
zipp                                  3.16.1

**Comment by PProfizi** [comment]
Hi @mcMunich,
The first thing I can see is that your `ansys-dpf-gate` and `ansys-dpf-gatebin` packages are out of sync, which could be a source of errors of the kind you showed first.
Please consider updating `ansys-dpf-gatebin` to 0.4.1.
I am in the process of merging of all these libraries within `ansys-dpf-core` so these kind of sync issues do not happen anymore and users have only one package to consider.

**Comment by mcMunich** [comment]
@PProfizi  That did it. I will put those two in my list of updates for my venv. Thanx!

**Comment by mcMunich** [comment]
@PProfizi  That did it. I will put those two in my list of updates for my venv. Thanx!
