### ISSUE TITLE
Dark mode font hardly readable

### ISSUE THREAD

**Issue by ayush-kumar-423** [ansys/pydpf-core#1144]
### Description of the modifications

![image](https://github.com/ansys/pydpf-core/assets/97742499/50868bf6-1e1a-4d12-b480-2fc2282b8127)

**Comment by ayush-kumar-423** [comment]
@PProfizi

**Comment by PProfizi** [comment]
Hi @ayush-kumar-423 ,
it may be linked to https://github.com/ansys/ansys-sphinx-theme/pull/282,
so I'll update `ansys-sphinx-theme` to the newest version and check if this solves the issue.

**Comment by ayush-kumar-423** [comment]
Thanks!

**Comment by PProfizi** [comment]
Updating `ansys-sphinx-theme` seems to solve this issue.
![image](https://github.com/ansys/pydpf-core/assets/100710998/fb40c7fc-58fd-4861-bed2-d3608ce88f40)
