### ISSUE TITLE
Running the example HDF5 export and import operations — PyDPF-Core (pyansys.com

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1188]
### Discussed in https://github.com/ansys/pydpf-core/discussions/1187

<div type='discussions-op-text'>

<sup>Originally posted by **Caroline-Poyser** October  9, 2023</sup>
Hi,
I am using python 3.8 and Ansys 2022 R2. I tried to run the example HDF5 export and import operations from the documentation https://dpf.docs.pyansys.com/version/stable/examples/05-file-IO/02-hdf5_serialize_and_read.html#sphx-glr-examples-05-file-io-02-hdf5-serialize-and-read-py
I am hitting the error on line 65 
AttributeError: 'Outputs' object has no attribute 'data_sources'

Could anybody explain why this is happening please</div>

**Comment by PProfizi** [comment]
Hello @Caroline-Poyser, 
Would it be possible for you to share the context in which you get this error please?
What I would be interested in is :
- your Ansys installation version, or DPF Server installation version
- the list of the packages installed in your Python environment when you get this error, using `pip list`

**Comment by Caroline-Poyser** [comment]
Hello @PProfizi, 
Thank you for looking at this. 
The DPF Server is version 4.0, Ansys 2022 R2,
The packages I have are shown below:
ansys-dpf-core           0.9.0    
ansys-dpf-gate           0.4.1    
ansys-dpf-gatebin        0.4.1    
ansys-grpc-dpf           0.8.1    
astroid                  3.0.0    
cachetools               5.3.1    
certifi                  2023.7.22
charset-normalizer       3.3.0    
colorama                 0.4.6    
contourpy                1.1.1    
cycler                   0.12.1  
dill                     0.3.7    
flake8                   6.1.0    
fonttools                4.43.1
google-api-core          2.12.0
google-api-python-client 2.102.0
google-auth              2.23.2
google-auth-httplib2     0.1.1
googleapis-common-protos 1.60.0
grpcio                   1.59.0
httplib2                 0.22.0
idna                     3.4
importlib-metadata       6.8.0
importlib-resources      6.1.0
isort                    5.12.0
kiwisolver               1.4.5
matplotlib               3.7.3
mccabe                   0.7.0
numpy                    1.24.4
packaging                23.2
Pillow                   10.0.1
pip                      21.1.1
platformdirs             3.11.0
pooch                    1.7.0
protobuf                 4.24.4
psutil                   5.9.5
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycodestyle              2.11.0
pyflakes                 3.1.0
pylint                   3.0.1
pyparsing                3.1.1
python-dateutil          2.8.2
pyvista                  0.42.3
requests                 2.31.0
rsa                      4.9
scooby                   0.7.4
setuptools               56.0.0
six                      1.16.0
tomli                    2.0.1
tomlkit                  0.12.1
tqdm                     4.66.1
typing-extensions        4.8.0
uritemplate              4.1.1
urllib3                  2.0.6
vtk                      9.2.6
zipp                     3.17.0  
I have attached a screenshot of the error
![error](https://github.com/ansys/pydpf-core/assets/147387894/9c16075a-ed6b-40b8-b286-dc8e28031fbf)

**Comment by PProfizi** [comment]
Hi @Caroline-Poyser, I think I found the issue:

The example uses the operator `hdf5dpf_generate_result_file` which only appears in the documentation of PyDPF-Core 0.9.0.
This operator is indeed only available starting with DPF 7.0 (Ansys 2024 R1 pre0).

This example should have been marked as requiring this minimal version, I'll update it right away.

In the meantime, if you wish to use this feature, what you can do is use DPF Server 2024.1.pre0 which is our standalone version of DPF (to install and use as a Python library), available following the directions [here](https://dpf.docs.pyansys.com/version/stable/user_guide/getting_started_with_dpf_server.html).
