### ISSUE TITLE
Failure of "Deploy stable docs index" job

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1234]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi @Revathyvenugopal162, do you have an idea of what might have gone wrong?
Failure of the `Deploy stable docs index` job in [releaser.yml](https://github.com/ansys/pydpf-core/blob/8b0180a3d720545b91f2452dff30b62dc7749b12/.github/workflows/releaser.yml#L79) during the latest release.

### Steps To Reproduce

https://github.com/ansys/pydpf-core/actions/runs/6579035067/job/17874194117

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.10

### Installed packages

NA

**Comment by PProfizi** [comment]
@jorgepiloto

**Comment by germa89** [comment]
It seems like a permission problem:

* https://stackoverflow.com/questions/60727752/error-cant-create-or-remove-files-in-install-directory-when-installing-by-sou
* https://askubuntu.com/questions/493312/permission-denied-error-when-using-easy-install

You could try to add `sudo` to the `pip install -e .`, in a proper branch, and then rerun your workflow with your action pointing to that branch.

It seems to me this action never ran completely (never use release with pymeilisearch) so it is difficult to know if something changed or something never was working.

Pinging @RobPasMue @Revathyvenugopal162

**Comment by PProfizi** [comment]
Linking the PR where `pymeilisearch` was added https://github.com/ansys/pydpf-core/pull/1179/files

**Comment by PProfizi** [comment]
Thx @RobPasMue, it doe shappen also on the dev doc

**Comment by PProfizi** [comment]
@RobPasMue  I can trigger the stable doc release again but I need to know if we must change something to the action first. We can test that by making a PR and updating the dev doc first.

**Comment by Revathyvenugopal162** [comment]
> I think this is related to the old token being re-deployed - @Revathyvenugopal162
> 
> Short term solution @PProfizi - retrigger the doc generation for the released docs. Redeploy them. And execute the meilisearch index generation for stable docs.
> 
> Is this only happening on stable docs? or also on dev docs?

yes, this is true, the is not showing any value. i dont see other issues in the PR which pymeilisearch implemented. @PProfizi  the issue here was https://github.com/ansys/pydpf-core/actions/runs/6579035067/job/17874194117 the pip install . was not working to get the version. if that got fixed, the deployment will not have any issues i hope

**Comment by PProfizi** [comment]
> > I think this is related to the old token being re-deployed - @Revathyvenugopal162
> > Short term solution @PProfizi - retrigger the doc generation for the released docs. Redeploy them. And execute the meilisearch index generation for stable docs.
> > Is this only happening on stable docs? or also on dev docs?
> 
> yes, this is true, the is not showing any value. i dont see other issues in the PR which pymeilisearch implemented. @PProfizi the issue here was https://github.com/ansys/pydpf-core/actions/runs/6579035067/job/17874194117 the pip install . was not working to get the version. if that got fixed, the deployment will not have any issues i hope

Ok, thx @Revathyvenugopal162 ! I'll try and fix that, then

**Comment by PProfizi** [comment]
@Revathyvenugopal162 I might need help understanding why the dev doc index deployment failed last time with many errors, despite the job being eventually green https://github.com/ansys/pydpf-core/actions/runs/6864191191/job/18666818212#step:2:6626
Is this normal?

**Comment by Revathyvenugopal162** [comment]
@PProfizi , the dumbing is correct and i can see the docs already deployed on the backend, so the indexing is correct. In dev docs, it is not showing the API key in raw HTML, 
![image](https://github.com/ansys/pydpf-core/assets/104772255/11bad205-df4b-446b-ab28-658aad0994ff)
Can you please confirm, "api_key": os.getenv("MEILISEARCH_PUBLIC_API_KEY", ""), in the conf file.if not adding this will solve the issue

**Comment by PProfizi** [comment]
Just merged a potential fix for the dev doc index deployment failure #1302
