### ISSUE TITLE
Automatically choose LegacyGrpc when on macOS

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1274]
### Description of the feature

When connecting to a remote server via `connect_to_server`, test if local machine is macOS and if so, set LegacyGrpc by default. 
Apparently trying out CGrpc first and setting back to LegacyGrpc after failure is not working properly all the time.

**Comment by germa89** [comment]
LegacyGrpc presents some limitations (for instance when working with the operator ``dpf.operators.result.mapdl_material_properties``. 

Is there any expectation to update the default macOS gRPC server to `CLayer gRPC`?? 

@PProfizi @rafacanton
