### ISSUE TITLE
Operators elastic_strain_eqv & mesh_to_pyvista

### ISSUE THREAD

**Issue by GitHubUser120282** [ansys/pydpf-core#1317]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi,
I want to use the following two operators, but it does not work ...

- Results of equivalent elastic strain using https://dpf.docs.pyansys.com/version/0.10/api/ansys.dpf.core.operators.result.elastic_strain_eqv.html#elastic-strain-eqv 
- KeyError: "The operator EPEL_EQV doesn't exist in the registry. Check its spelling in the documentation or verify its availability in your loaded plugins. The current available operator names can be accessed using 'available_operator_names' method."
 
- Mesh to PyVista using https://dpf.docs.pyansys.com/version/0.10/api/ansys.dpf.core.operators.mesh.mesh_to_pyvista.html#mesh-to-pyvista
- KeyError: "The operator mesh_to_pyvista doesn't exist in the registry. Check its spelling in the documentation or verify its availability in your loaded plugins. The current available operator names can be accessed using 'available_operator_names' method."

How can I solve the issue? Thanks for help.

### Steps To Reproduce

```py
from ansys.dpf import core as dpf

FNAME='flange' #ANSYS RST file

MODEL=dpf.Model(FNAME+'.rst')
MESH=MODEL.metadata.meshed_region
LIST=dpf.dpf_operator.available_operator_names()
for op in LIST:
    if 'EPEL_EQV' in op:
        print (op)
    if 'EPPL_EQV' in op:
        print (op)
    if 'mesh_to_pyvista' in op:
        print (op)

RES_SC=dpf.operators.result.stress(data_sources=MODEL).eval()  
RES_EE=dpf.operators.result.elastic_strain(data_sources=MODEL).eval()  

RES_EE=dpf.operators.result.elastic_strain_eqv(data_sources=MODEL).eval() 
#KeyError: "The operator EPEL_EQV doesn't exist in the registry. Check its spelling in the documentation or verify its availability in your loaded plugins. The current available operator names can be accessed using 'available_operator_names' method."

MESH_=dpf.operators.mesh.mesh_to_pyvista(mesh=MESH) 
#KeyError: "The operator mesh_to_pyvista doesn't exist in the registry. Check its spelling in the documentation or verify its availability in your loaded plugins. The current available operator names can be accessed using 'available_operator_names' method."
```

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2023 R1

### Which Python version causes the issue?

3.11

### Installed packages

Package                  Version
------------------------ ----------
ansys-dpf-core           0.10.0
ansys-dpf-post           0.6.0
cachetools               5.3.2
certifi                  2023.11.17
charset-normalizer       3.3.2
colorama                 0.4.6
contourpy                1.0.7
cycler                   0.11.0
fonttools                4.39.2
google-api-core          2.14.0
google-api-python-client 2.109.0
google-auth              2.25.1
google-auth-httplib2     0.1.1
googleapis-common-protos 1.61.0
grpcio                   1.59.3
httplib2                 0.22.0
idna                     3.6
importlib-metadata       7.0.0
kiwisolver               1.4.4
matplotlib               3.8.2
numpy                    1.26.2
packaging                23.0
Pillow                   9.4.0
pip                      23.3.1
platformdirs             4.1.0
pooch                    1.8.0
protobuf                 4.25.1
psutil                   5.9.6
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pyparsing                3.0.9
pypdf                    3.17.1
PyQt5                    5.15.10
PyQt5-Qt5                5.15.2
PyQt5-sip                12.13.0
python-dateutil          2.8.2
pyvista                  0.42.3
pywin32                  306
requests                 2.31.0
rsa                      4.9
scipy                    1.11.4
scooby                   0.9.2
setuptools               65.5.0
six                      1.16.0
tqdm                     4.66.1
uritemplate              4.1.1
urllib3                  2.1.0
vtk                      9.3.0
xlwings                  0.30.12
zipp                     3.17.0

**Comment by PProfizi** [comment]
Hello @GitHubUser120282,
These errors usually happen due to issues with the installation.
I see you already test whether the operators are listed in `dpf.dpf_operator.available_operator_names()`.
Does this mean that the prints return `True` but the commands still fail with the `KeyError`?
If the prints testing `LIST` return `False`, then the problem is definitely with the server starting.

**Comment by GitHubUser120282** [comment]
Thanks for your reply. So what can I do to use both operators (EPPL_EQV and mesh_to_pyvista)? Is the problem on my side or on the server side?

**Comment by PProfizi** [comment]
@GitHubUser120282 We'll to find out why the server instance you start does not have these operators registered. @rafacanton any idea as to why these in particular would be missing?

**Comment by rafacanton** [comment]
@GitHubUser120282 , @PProfizi both `EPPL_EQV` and `mesh_to_pyvista` are part of plugins that should be loaded by default in both the Ansys Unified Install and DPF Standalone Server contexts. Do you see any prints in the loop you show?

**Comment by rafacanton** [comment]
@GitHubUser120282 I can see EPPL_EQV there: 

![image](https://github.com/ansys/pydpf-core/assets/107186344/ef5c512a-aa37-4247-9372-0640f2cc6e6c)

Regarding `mesh_to_pyvista`, it was coded for Ansys 2023 R2, and I can see that you are using 2023 R1 as server, that explains it.

**Comment by rafacanton** [comment]
@GitHubUser120282 Sorry, I was looking at `EPPEL_EQV` instead of `EPEL_EQV`. This was a missing feature that was added also in 2023 R2. This explains the reason of not having it available.

**Comment by GitHubUser120282** [comment]
Super. Next year I will install ANSYS 2024 R1. Thank you very much ...
By the way, can I see in the help which version is required for a results operator?

**Comment by PProfizi** [comment]
@GitHubUser120282 sadly not yet, or you can but it is not straightforward. This is one of our main enhancement requests though.
What you can do in the meantime is open the pydpf-core doc of the [first version released compatible with your server](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1). Then you can be certain only available operators are listed.
