### ISSUE TITLE
Add operator to read .h5 files to Fields/Fields Containers

### ISSUE THREAD

**Issue by MichaelBThompson** [ansys/pydpf-core#1320]
### Description of the feature

There is an operator to serialize to .h5 file from a Fields Container.  I would like the inverse operator to read an .h5 file into a DPF data structure.  This would obviously be limited to the format in which DPF writes to .h5 and couldn't read ANY .h5 file.
There is a csv to field operator that is of a similar implementation.

### Steps for implementing the feature

Create new operator as indicated.

**Comment by rafacanton** [comment]
@MichaelBThompson This operator already exists. If you have a dpf-generated .h5 file, you can generate a dataSources from it giving it a `"h5dpf"` key:

```
ds = dpf.DataSources()
ds.set_result_file(path_to_h5, "h5dpf")
```

And then the regular operators (results providers, mesh provider, time freq provider...) should work out of the box

**Comment by MichaelBThompson** [comment]
[like]  Michael Thompson reacted to your message:
________________________________
