### ISSUE TITLE
PyDPF documentation search doesn't work

### ISSUE THREAD

**Issue by ayush-kumar-423** [ansys/pydpf-core#1327]
### Description of the modifications

PyDPF documentation search doesn't work - it was resolved some time back but now it doesn't work.
The first search returns a blank page. Searching again on that blank page gives a cropped drop-down of results.

![image](https://github.com/ansys/pydpf-core/assets/97742499/f819ce1e-eddc-4b92-baf7-64eaa8dd6ea6)

**Comment by PProfizi** [comment]
@Revathyvenugopal162 do you think you could have a look?
 it seems there is no link between what's put in the search bar on the top-right and what ends-up in the actual search engine.
Also the result is cropped on the left side as we already discussed.
![image](https://github.com/ansys/pydpf-core/assets/100710998/659e7191-b312-432c-8002-1048a655eb80)

**Comment by ayush-kumar-423** [comment]
@Revathyvenugopal162 and @PProfizi can we please prioritize this issue? This is an important one.

cc: @rlagha, @smedikon, @MaxJPRey, @pmaroneh

**Comment by MaxJPRey** [comment]
Adding @jorgepiloto for visibility.

**Comment by jorgepiloto** [comment]
Hi @ayush-kumar-423, thanks for reporting this issue. I can reproduce, the search bar does not work. Let me investigate a bit more.

**Comment by ayush-kumar-423** [comment]
Hi @jorgepiloto, @PProfizi 

Unfortunately, it still doesn't work (see screenshot below), the results are still cropped and the first search doesn't provide any results:
![image](https://github.com/ansys/pydpf-core/assets/97742499/5c2453e7-c8ba-43f9-98e8-ed7db4ab9561)

**Comment by jorgepiloto** [comment]
Hi @ayush-kumar-423. I opened https://github.com/ansys/pydpf-core/pull/1401. I am clueless about why the Meilisearch CSS and JS is not being injected in the HTML files.

**Comment by ayush-kumar-423** [comment]
Thanks @jorgepiloto, seems it is generic. Same for PyMAPDL doc.

**Comment by Revathyvenugopal162** [comment]
The issue has been resolved in https://github.com/ansys/pydpf-core/pull/1401, and now the search function is working as intended.https://dpf.docs.pyansys.com/version/dev/index.html. So closing the issue.
