### ISSUE TITLE
Reading Results for Large *.rst files failed

### ISSUE THREAD

**Issue by GitHubUser120282** [ansys/pydpf-core#1333]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi,
I want to extract reaction forces for certain nodes and stresses & strains for certain elements. It works very well, but when the *.rst file gets larger, it fails, e.g. for size of 20GB. Then I reduced the *.rst file to 5GB (using outres in ANSYS), then it works again.
For the 20GB, I can read out the results (20 substeps) for some substeps (1,2,3,4,5,6,7,8,9,19 & 20), but for the other substeps (10-18) I get the error "OSError: exception: access violation reading 0x0000000000000030", see following image.

![image](https://github.com/ansys/pydpf-core/assets/153374639/746dbf16-8cc3-4c93-ac7b-63513310db87)

Thanks for feedback. Please let me know if more information is required.

### Steps To Reproduce

Operators used
 RES_RF=dpf.operators.result.reaction_force(data_sources=MODEL,time_scoping=ID_STEPS,mesh_scoping=ID_NODES,bool_rotate_to_global=None).eval()
RES_SC=dpf.operators.result.stress(data_sources=MODEL,time_scoping=ID_STEPS,mesh_scoping=ID_ELEMS,bool_rotate_to_global=True,requested_location='ElementalNodal').eval()

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2023 R1

### Which Python version causes the issue?

3.11

### Installed packages

Package                  Version
------------------------ ----------
ansys-dpf-core           0.10.0
ansys-dpf-post           0.6.0
cachetools               5.3.2
certifi                  2023.11.17
charset-normalizer       3.3.2
colorama                 0.4.6
contourpy                1.0.7
cycler                   0.11.0
fonttools                4.39.2
google-api-core          2.14.0
google-api-python-client 2.109.0
google-auth              2.25.1
google-auth-httplib2     0.1.1
googleapis-common-protos 1.61.0
grpcio                   1.59.3
httplib2                 0.22.0
idna                     3.6
importlib-metadata       7.0.0
kiwisolver               1.4.4
matplotlib               3.8.2
numpy                    1.26.2
packaging                23.0
Pillow                   9.4.0
pip                      23.3.1
platformdirs             4.1.0
pooch                    1.8.0
protobuf                 4.25.1
psutil                   5.9.6
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pyparsing                3.0.9
pypdf                    3.17.1
PyQt5                    5.15.10
PyQt5-Qt5                5.15.2
PyQt5-sip                12.13.0
python-dateutil          2.8.2
pyvista                  0.42.3
pywin32                  306
requests                 2.31.0
rsa                      4.9
scipy                    1.11.4
scooby                   0.9.2
setuptools               65.5.0
six                      1.16.0
tqdm                     4.66.1
uritemplate              4.1.1
urllib3                  2.1.0
vtk                      9.3.0
xlwings                  0.30.12
zipp                     3.17.0

**Comment by PProfizi** [comment]
Hi @GitHubUser120282,
Thanks for raising this issue.
Considering the size of the result file, could you please indicate how much RAM you have on your machine?
In your case, it may help to use an `incremental evaluator`, which makes the operators process the data in chunks and becomes necessary for large files depending on your hardware.
You can find an example of how to use it [here](https://dpf.docs.pyansys.com/version/stable/examples/04-advanced/14-incremental_evaluation.html).
Please do not hesitate to ask for support on how to adapt your script, or if this does not solve your problem.

**Comment by GitHubUser120282** [comment]
Thanks for the feedback. 

The machine has 126 GB RAM. I think it is not a problem of RAM, as I can extract results for some substeps.
I can try the incremental approach. At the moment I use  

RES_RF=dpf.operators.result.reaction_force(data_sources=MODEL,time_scoping=ID_STEPS,mesh_scoping=ID_NODES,bool_rotate_to_global=None).eval()

How do I have to modify it?

**Comment by GitHubUser120282** [comment]
Good to know. I will try it next year with ANSYS 2024 R1. At the moment we can reduce the rst files by outres in ANSYS, but for the future it is nice to have all the results. Thanks for the help ...
PS: I will of course give you an update when I will re-run the analysis.
