### ISSUE TITLE
NMISC and SMISC retrocompatibility break

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1438]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Operators `dpf.operators.result.nmisc` and `dpf.operators.result.smisc` in PyDPF-Core 0.11.0 are not retro-compatible with DPF servers below `2024.2.pre0` due to breaking changes server-side.
We need to see how to properly manage that.

### Steps To Reproduce

NA

### Which Operating System causes the issue?

Windows, MacOS, Linux

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.11

### Installed packages

NA

**Comment by PProfizi** [comment]
@ayush-kumar-423 @rafacanton

**Comment by germa89** [comment]
For the record:

https://github.com/ansys/pymapdl/actions/runs/8066167024/job/22033628509#step:17:430

**Comment by kmahajan-cadfem** [comment]
I have also just noticed it, would this be addressed or the existing scripts have to be changed for future compatibility?

**Comment by germa89** [comment]
Any update on this?? @PProfizi @rafacanton

**Comment by rhooff** [comment]
The problem also occurs when a Mechanical rst file from 23R1 is postprocessed with ansys-dpf-core 0.12.0 and Python 3.9.0 and using the following code:

smisc34=dpf.operators.result.smisc(data_sources=my_data_sources,
                                   mesh_scoping=scoping_beam_elem,
                                   item_index=34)

A workaround is to use: 

smisc34 = model.operator("mapdl::smisc")
smisc34.connect(1,scoping_beam_elem)
smisc34.connect(4,my_data_sources)
smisc34.connect(10,34) #item index 34 - SBzT
smisc34.connect(11,1) #1 component 1

The values that are returned are NOT identical to those for a User Defined Result in Mechanical with smisc34. The unit should be N/m^2 but the returned unit shows m^2.

[smisc34_24R1_general_method.txt](https://github.com/ansys/pydpf-core/files/15237114/smisc34_24R1_general_method.txt)

**Comment by germa89** [comment]
> Any update on this?? @PProfizi @rafacanton

Again.... are they any plans to bring back those operators? If not, we should close this issue.

**Comment by rafacanton** [comment]
@germa89 Unfortunately we broke retro with a mistake and the operators will not be available again. I think that in client applications for this result you can do an ugly `if` based on the dpf version (which you can know doing a `dpf.global_server().version`):

- If dpf version >= 8.0 ( = 24.2.pre0 as per [this table](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1)) the internal operator to be run should be `"NMISC"/"SMISC"`, which is mapped to the regular `dpf.operators.result.nmisc/dpf.operators.result.smisc`.
- For older versions, the internal operator to be run should be `"mapdl::nmisc"/"mapdl::smisc"`, which are always accessible in that versions through the less Pythonic APIs `dpf.Operator("mapdl::nmisc")/dpf.Operator("mapdl::smisc")`.
