### ISSUE TITLE
pyDPF core operator property_field_provider_by_name() not working

### ISSUE THREAD

**Issue by Louise-Ramos** [ansys/pydpf-core#1459]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The pyDPF core metadata property_field_provider_by_name() is not working.
When the operator is called, an error message saying that the operator does not exists is shown.

Error message : KeyError: "The operator property_field_provider_by_name doesn't exist in the registry. Check its spelling in the documentation or verify its availability in your loaded plugins. The current available operator names can be accessed using 'available_operator_names' method."

### Steps To Reproduce

Run the following commands changing the 'file.rst' by an available rst file :

from ansys.dpf.core import Model
from ansys.dpf import core as dpf

model = Model( 'file.rst');
my_data_sources = model.metadata.data_sources
op = dpf.operators.metadata.property_field_provider_by_name()

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2022 R2

### Which Python version causes the issue?

3.11

### Installed packages

annotated-types 0.6.0
ansys-additive-core 0.17.2
ansys-api-additive 1.4.1
ansys-api-dbu 0.2.5
ansys-api-dyna 0.3.6
ansys-api-edb 1.0.0
ansys-api-fluent 0.3.22
ansys-api-geometry 0.3.8
ansys-api-mapdl 0.5.1
ansys-api-mechanical 0.1.1
ansys-api-meshing-prime 0.1.2
ansys-api-platform-instancemanagement 1.0.0
ansys-api-pyensight 0.3.4
ansys-api-sherlock 0.1.22
ansys-api-systemcoupling 0.1.0
ansys-dpf-composites 0.4.0
ansys-dpf-core 0.10.1
ansys-dpf-gate 0.4.1
ansys-dpf-gatebin 0.4.1
ansys-dpf-post 0.6.0
ansys-dyna-core 0.4.12
ansys-dynamicreporting-core 0.5.1
ansys-edb-core 0.1.3
ansys-fluent-core 0.18.2
ansys-geometry-core 0.4.11
ansys-grantami-bomanalytics 2.0.0
ansys-grantami-bomanalytics-openapi 2.0.0
ansys-grantami-recordlists 1.1.0
ansys-grantami-serverapi-openapi 2.0.0
ansys-grpc-dpf 0.8.1
ansys-hps-client 0.7.1
ansys-mapdl-core 0.67.0
ansys-mapdl-reader 0.52.20
ansys-math-core 0.1.3
ansys-mechanical-core 0.10.7
ansys-mechanical-env 0.1.3
ansys-meshing-prime 0.5.1
ansys-motorcad-core 0.4.2
ansys-openapi-common 1.5.1
ansys-optislang-core 0.6.1
ansys-platform-instancemanagement 1.1.2
ansys-pyensight-core 0.7.5
ansys-pythonnet 3.1.0rc3
ansys-rocky-core 0.1.0
ansys-seascape 0.2.0
ansys-sherlock-core 0.4.0
ansys-simai-core 0.1.4
ansys-systemcoupling-core 0.4.1
ansys-tools-path 0.4.0
ansys-turbogrid-api 0.4.0
ansys-turbogrid-core 0.4.0
appdirs 1.4.4
asgiref 3.7.2
backoff 2.2.1
bcrypt 4.1.2
beartype 0.17.2
bleach 6.1.0
bokeh 3.3.4
build 1.0.3
cachetools 5.3.1
certifi 2023.7.22
cffi 1.16.0
charset-normalizer 3.3.0
click 8.1.7
clr-loader 0.2.6
colorama 0.4.6
contourpy 1.1.1
coverage 7.3.3
cryptography 41.0.4
cycler 0.12.1
decorator 5.1.1
defusedxml 0.7.1
Deprecated 1.2.14
dill 0.3.8
Django 4.2.6
docker 7.0.0
docutils 0.20.1
ecdsa 0.18.0
elementpath 4.3.0
fabric 3.2.2
filelock 3.12.4
fonttools 4.43.1
fpdf2 2.7.8
geomdl 5.3.1
google-api-core 2.12.0
google-api-python-client 2.103.0
google-auth 2.23.3
google-auth-httplib2 0.1.1
googleapis-common-protos 1.60.0
grpcio 1.59.0
grpcio-health-checking 1.48.2
grpcio-status 1.48.2
h5py 3.10.0
httplib2 0.22.0
idna 3.4
imageio 2.28.0
imageio-ffmpeg 0.4.9
importlib-metadata 6.8.0
iniconfig 2.0.0
invoke 2.2.0
jaraco.classes 3.3.0
Jinja2 3.1.3
keyring 24.2.0
kiwisolver 1.4.5
linkify-it-py 2.0.3
lxml 4.9.3
Markdown 3.5.2
markdown-it-py 3.0.0
MarkupSafe 2.1.5
marshmallow 3.21.1
marshmallow-oneofschema 3.1.1
matplotlib 3.8.0
mdit-py-plugins 0.4.0
mdurl 0.1.2
more-itertools 10.1.0
nh3 0.2.14
numpy 1.25.2
packaging 23.2
pandas 2.1.1
panel 1.3.8
param 2.0.2
paramiko 3.4.0
Pillow 10.0.1
Pint 0.23
pip 23.3.1
pkginfo 1.9.6
platformdirs 3.11.0
plotly 5.19.0
pluggy 1.3.0
plumbum 1.8.2
pooch 1.7.0
protobuf 3.20.3
psutil 5.9.5
pyaedt 0.7.10
pyansys 2024.1.6
pyansys-docker 5.0.4
pyansys-tools-versioning 0.5.0
pyasn1 0.5.0
pyasn1-modules 0.3.0
pycparser 2.21
pydantic 2.6.3
pydantic_core 2.16.3
Pygments 2.16.1
pygranta 2024.1.0
pyiges 0.3.1
PyNaCl 1.5.0
pyparsing 3.1.1
pypiwin32 223
pypng 0.20220715.0
pyproject_hooks 1.0.0
Pyro5 5.15
pyspnego 0.10.2
pytest 7.4.3
pytest-cov 4.1.0
python-dateutil 2.8.2
python-jose 3.3.0
python-keycloak 2.0.0
pythonnet 3.0.1
pytwin 0.6.0
pytz 2023.3.post1
pyvista 0.42.3
pyviz_comms 3.0.1
pywin32 306
pywin32-ctypes 0.2.2
PyYAML 6.0.1
readme-renderer 42.0
requests 2.31.0
requests-negotiate-sspi 0.5.2
requests-ntlm 1.2.0
requests-toolbelt 1.0.0
rfc3986 2.0.0
rich 13.6.0
rpyc 5.3.1
rsa 4.9
scipy 1.11.3
scooby 0.7.4
semver 3.0.2
serpent 1.41
setuptools 65.5.1
six 1.16.0
sqlparse 0.4.4
sseclient-py 1.8.0
sspilib 0.1.0
tenacity 8.2.3
tomli 2.0.1
tornado 6.4
tqdm 4.66.1
twine 4.0.2
typing 3.7.4.3
typing_extensions 4.8.0
tzdata 2023.3
uc-micro-py 1.0.3
uritemplate 4.1.1
urllib3 1.26.17
vtk 9.2.6
wakepy 0.7.2
webencodings 0.5.1
websocket-client 1.6.4
wheel 0.38.4
wrapt 1.16.0
xmlschema 2.5.1
xyzservices 2023.10.1
zipp 3.17.0

**Comment by PProfizi** [comment]
Hello @Louise-Ramos, it looks like you are using Ansys 2022R2, and the mesh_property_provider operator was not available in this version.
It was introduced in Ansys 2023R1. Sadly the operators do not state in their documentation which minimal DPF version they require, we are working on it.
Do not hesitate to use the latest release of [DPF as a standalone](https://dpf.docs.pyansys.com/version/stable/getting_started/dpf_server.html) if upgrading your Ansys installation is not possible.
