### ISSUE TITLE
Getting reaction "force" using dpf for thermal simulations

### ISSUE THREAD

**Issue by JimmyHe0527** [ansys/pydpf-core#1477]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

A few issues were observed:
1. When extracting the reaction force on a set of nodes using the element_nodal_forces operator in mech-dpf, the behaviors are different between structural simulations (.rst files) and thermal simulations (.rth files). More specifically:
1(a): When summing all the nodal contributions, code gives right result for structural reaction force for .rst file but not for the total heat rate for .rth file.
1(b): Code works fine for both linear and quadratic elements for .rst file, but fails to execute for linear element in .rth file.

2. The equivalent standalone dpf code shows similar issues: correct results for .rst file but not .rth file. The standalone dpf code also does not work for linear elements in .rth file.

The minimum example can be found here: 
[MWE.zip](https://github.com/ansys/pydpf-core/files/14696222/MWE.zip)

### Steps To Reproduce

Using the provided minimum example:
1. Solve both analyses to generate results files.
2. Run the mech-dpf code in the Mechanical scripting window.
3. Run the standalone DPF code in CPython virtual environment.

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.10

### Installed packages

Package                  Version
------------------------ --------
ansys-dpf-core           0.11.0
cachetools               5.3.3
certifi                  2024.2.2
charset-normalizer       3.3.2
colorama                 0.4.6
google-api-core          2.17.1
google-api-python-client 2.122.0
google-auth              2.28.2
google-auth-httplib2     0.2.0
googleapis-common-protos 1.63.0
grpcio                   1.62.1
httplib2                 0.22.0
idna                     3.6
importlib_metadata       7.0.2
numpy                    1.26.4
packaging                24.0
pip                      23.0.1
protobuf                 4.25.3
psutil                   5.9.8
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pyparsing                3.1.2
requests                 2.31.0
rsa                      4.9
setuptools               65.5.0
tqdm                     4.66.2
uritemplate              4.1.1
urllib3                  2.2.1
zipp                     3.18.1

**Comment by oparreno** [comment]
Hi @JimmyHe0527 , setting split_force_components to true should allow you to match reactions for thermal analysis.

Also, if you're interested in calculating thermal reactions, you could try the operator "force_summation", this will perform operations similar to MAPDL FSUM based on a nodal and elemental scoping.
