### ISSUE TITLE
Please add option for parallel views 

### ISSUE THREAD

**Issue by ZanePC** [ansys/pydpf-core#1532]
### Description of the feature

At present, models can only be displayed in perspective view in ansys-dpf, but in most cases parallel view is better (because it prevents the model from being deformed due to viewing). There is already a parameter "parallel_projection" in the pyvista.plot() function, but it does not work if the parameter is specified as True in ansys-dpf.

**Comment by PProfizi** [comment]
Hi @ZanePC, just made a small PR so that our plotting methods all take into account `parallel_projection=True` as kwarg.
Let me know if this is sufficient.

**Comment by ZanePC** [comment]
Thank you very much for your quick response. I will try it immediately after v0.12.1 is released. Best wishes.
