### ISSUE TITLE
Stable doc search is broken

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1538]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Search in stable doc is broken, see https://dpf.docs.pyansys.com/version/stable/index.html
The loading icon keeps turning but nothing ever appears.
Dev doc and previous versions docs are working fine.

### Steps To Reproduce

The deployment job to look at is: https://github.com/ansys/pydpf-core/actions/runs/8661875996/job/23752909974
A reference deployment job (for 0.11.0) can be found here: https://github.com/ansys/pydpf-core/actions/runs/7989894623/job/21817574944
I think the problem may be with the meilisearch for `stable`.

### Which Operating System causes the issue?

Windows, MacOS, Linux

### Which DPF/Ansys version are you using?

DPF Server 2024.2.pre1

### Which Python version causes the issue?

3.11

### Installed packages

NA

**Comment by PProfizi** [comment]
Hi @Revathyvenugopal162, the meilisearch bar stopped working on our stable doc, (it hangs indefinitely) do you know what could be causing this?
The stable index deployment job seems to have worked fine as far as I can tell... Is it possible it is a problem with the Meilisearch service?

**Comment by Revathyvenugopal162** [comment]
> Hi @Revathyvenugopal162, the meilisearch bar stopped working on our stable doc, (it hangs indefinitely) do you know what could be causing this? The stable index deployment job seems to have worked fine as far as I can tell... Is it possible it is a problem with the Meilisearch service?

sure, let me check.

**Comment by jorgepiloto** [comment]
This is working now. Should we close the issue?

**Comment by PProfizi** [comment]
Hi @jorgepiloto , @Revathyvenugopal162 , I guess the latests releases fixed that, most likely due to upgrades in the pyansys actions used. Closing this issue? Thanks both!
