### ISSUE TITLE
Bug located in reading main_title from the rst file

### ISSUE THREAD

**Issue by rajesh1359** [ansys/pydpf-core#1543]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

While reading the main_title from rst file, dpf read until the first space encountered ( Refer to image below)

`import ansys.dpf.core as dpf
model = dpf.Model(file_path)

op = dpf.operators.metadata.result_info_provider(
    data_sources=model.metadata.data_sources,
)

result_result_info = op.outputs.result_info()`

![image](https://github.com/ansys/pydpf-core/assets/60212378/efe9aa02-56fd-44ea-aa19-3658e59c282e)

### Steps To Reproduce

...

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

DPF Server 2024.2.pre1

### Which Python version causes the issue?

3.10

### Installed packages

...

**Comment by PProfizi** [comment]
Confirm fixed
