### ISSUE TITLE
Repeatedly launching the dpf server fails

### ISSUE THREAD

**Issue by andreas-hilti** [ansys/pydpf-core#1579]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

After about 120 successful launches, start_local_server fails with 
`RuntimeError: The input line is too long`.
This is on Windows.

### Steps To Reproduce

Run this snippet on Windows:
```
import ansys.dpf.core as dpf
for i in range(200):
    print(i)
    server = dpf.start_local_server(config=dpf.AvailableServerConfigs.GrpcServer, as_global=False)
    server.release()
```

Will result in after about 120 successful calls in:
```
Traceback (most recent call last):
  File "D:\ANSYSDev\data-model\etc\python\scripts\launch_bug copy.py", line 4, in <module>
    server = dpf.start_local_server(config=dpf.AvailableServerConfigs.GrpcServer, as_global=False)
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server.py", line 232, in start_local_server
    server = server_type(
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 724, in __init__
    launch_dpf(ansys_path, ip, port, timeout=timeout)
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 199, in launch_dpf
    _wait_and_check_server_connection(
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 173, in _wait_and_check_server_connection
    raise RuntimeError(errstr)
RuntimeError: The input line is too long.

The syntax of the command is incorrect.

D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py:617: UserWarning: Traceback (most recent call last):
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 607, in __del__
    if server() == self:
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 807, in __eq__
    return self.address == other_server.address
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 822, in address
    return self._address
AttributeError: 'GrpcServer' object has no attribute '_address'

  warnings.warn(traceback.format_exc())
D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py:665: UserWarning: Traceback (most recent call last):
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\core\server_types.py", line 663, in __del__
    self._deleter_func[0](self._deleter_func[1](self))
  File "D:\ANSYSDev\data-model\test_env\lib\site-packages\ansys\dpf\gate\generated\data_processing_capi.py", line 123, in data_processing_delete_shared_object
    res = capi.dll.DataProcessing_delete_shared_object(data._internal_obj if data is not None else None, ctypes.byref(utils.to_int32(errorSize)), ctypes.byref(sError))
AttributeError: 'GrpcClient' object has no attribute '_internal_obj'

  warnings.warn(traceback.format_exc())
```

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.10

### Installed packages

Package                  Version
------------------------ --------
ansys-dpf-core           0.12.1
cachetools               5.3.3
certifi                  2024.2.2
charset-normalizer       3.3.2
colorama                 0.4.6
google-api-core          2.19.0
google-api-python-client 2.129.0
google-auth              2.29.0
google-auth-httplib2     0.2.0
googleapis-common-protos 1.63.0
grpcio                   1.64.0
httplib2                 0.22.0
idna                     3.7
importlib_metadata       7.1.0
numpy                    1.26.4
packaging                24.0
pip                      22.3.1
proto-plus               1.23.0
protobuf                 4.25.3
psutil                   5.9.8
pyasn1                   0.6.0
pyasn1_modules           0.4.0
pyparsing                3.1.2
requests                 2.32.1
rsa                      4.9
setuptools               65.5.0
tqdm                     4.66.4
uritemplate              4.1.1
urllib3                  2.2.1
zipp                     3.18.2

**Comment by andreas-hilti** [comment]
Note:
This might be related:
https://stackoverflow.com/questions/682799/what-to-do-with-the-input-line-is-too-long-error-message

**Comment by PProfizi** [comment]
Hi @andreas-hilti FYI I got the same issue when trying to upgrade `pytest` from `7.*` to `8.*`, see [here](https://github.com/ansys/pydpf-core/pull/1540). 
I haven't seen this error anywhere else before so maybe it is linked.
I was investigating this last Friday but did not see anything which could be the source in the [pytest changelog for 8.0rc1](https://docs.pytest.org/en/8.1.x/changelog.html#pytest-8-0-0rc1-2023-12-30)

**Comment by andreas-hilti** [comment]
@PProfizi Good to know, but it must be another dependency as in the venv that I used to reproduce it, pytest is not even installed...

**Comment by PProfizi** [comment]
> @PProfizi Good to know, but it must be another dependency as in the venv that I used to reproduce it, pytest is not even installed...

I'll cross-reference the dependencies in your case and in my case and see what could be the culprit.

**Comment by andreas-hilti** [comment]
@PProfizi Interesting is that this seems to work:
```
import os
orgpath=os.environ["PATH"]
import ansys.dpf.core as dpf
for i in range(200):
    os.environ["PATH"]=orgpath
    print(i)
    server = dpf.start_local_server(config=dpf.AvailableServerConfigs.GrpcServer, as_global=False)
    server.release()
```
Seems like the issue is that the PATH env variable is getting too long...

**Comment by PProfizi** [comment]
Can confirm this is only for `dpf.AvailableServerConfigs.GrpcServer`.
The others work fine.

**Comment by PProfizi** [comment]
Can confirm this is not due to PATH manipulations in `ansys.dpf.gate.load_api.py/load_grpc_client`.
I could clearly see however that the PATH had increased in size between each call to `load_grpc_client` (thus between each call to `start_local_server`)

**Comment by PProfizi** [comment]
Ok, found the culprit https://github.com/ansys/pydpf-core/blob/e3b58f1649af79c2d70a578ac4d6084331cdac65/src/ansys/dpf/core/server_factory.py#L611
Will start a PR with a fix
