### ISSUE TITLE
Invalid specifier: '>=3.7.* on python version 3.12

### ISSUE THREAD

**Issue by RaphaelHeiniger** [ansys/pydpf-core#1596]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Installing DPF server fails with the error:

_`PS C:\Users\rheinige\Downloads\ansys_dpf_server_win_v2023.2.pre1> pip install -e .
Obtaining file:///C:/Users/rheinige/Downloads/ansys_dpf_server_win_v2023.2.pre1
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
 
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in ansys-dpf-server_2023_2_pre1 setup command: 'python_requires' must be a string containing valid version specifiers; **Invalid specifier: '>=3.7.*'**
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
 
× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.`_

FIX:
editing setup.py from python_requires=">=3.7.*,<4.0" to python_requires=">=3.7,<4.0" solved the issue.

AFFECTED VERSIONS:
**this error only occures with dpf server versions ansys_dpf_server_win_v2023.2.pre1 or ansys_dpf_server_win_v2023.2.pre0**
in newer ones the setup.py is already equal to python_requires=">=3.7,<4.0"

### Steps To Reproduce

Install python version 3.12
Download unzip ansys_dpf_server_win_v2023.2.pre1 or ansys_dpf_server_win_v2023.2.pre0 from https://download.ansys.com/Others/DPF%20Pre-Release
Try to install

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

DPF Server 2023.2.pre1, DPF Server 2023.2.pre0

### Which Python version causes the issue?

3.12

### Installed packages

PS C:\Users\rheinige\Downloads\ansys_dpf_server_win_v2023.2.pre0> py -m pip list
Package                      Version      Editable project location
---------------------------- ------------ -------------------------------------------------------------
ansys-dpf-server_2023_2_pre0 2023.2rc0    C:\Users\rheinige\Downloads\ansys_dpf_server_win_v2023.2.pre0
argcomplete                  3.1.6
click                        8.1.7
colorama                     0.4.6
contourpy                    1.2.0
cycler                       0.12.1
fonttools                    4.46.0
kiwisolver                   1.4.5
matplotlib                   3.8.2
numpy                        1.26.2
packaging                    23.2
pandas                       2.1.4
Pillow                       10.1.0
pip                          24.0
pipx                         1.2.1
pyparsing                    3.1.1
python-dateutil              2.8.2
pytz                         2023.3.post1
scipy                        1.11.4
six                          1.16.0
tzdata                       2023.3
userpath                     1.9.1

**Comment by PProfizi** [comment]
Hello @RaphaelHeiniger, we are aware of this issue, which as you saw we fixed in the packaging of `DPF server 2024.1` onwards.
After discussing this again with the team, the policy is that we do not release patch versions of the `pre` releases of DPF.
I am thus closing this as will not solve, but thanks again for raising the issue so people can refer to it if necessary.
