### ISSUE TITLE
Search bar is slow

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1598]
### Description of the modifications

When searching in the dev doc for `Field` or `lsdyna`, the search takes 5 to 6 seconds which is too long (for example compared to pymapdl doc). Maybe a problem with the doc structure?
@jor

**Comment by jorgepiloto** [comment]
Hi Paul, this is working smooth for me. It takes less than a second to load the results for `Field`. Writing `LS` quickly triggers the suggestions on LS-Dyna.

My connection speed is 600Mbit/s.

**Comment by PProfizi** [comment]
Hi all, thanks for checking this. I guess the new releases improved this. Closing the issue.
