### ISSUE TITLE
problem installing 2024R1 DPF server

### ISSUE THREAD

**Issue by TommasoMarella** [ansys/pydpf-core#1623]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Even if I have installed 2024R1 Ansys in my linux machine, it tries to connect to 19.2 version (which doesn't support dpf):
![image](https://github.com/ansys/pydpf-core/assets/134281689/ad43a593-2275-44cf-ba92-3c4b0338cd0a)

I tried also to start a local server for 2024R1 and doesn't work (see image above)

### Steps To Reproduce

.

### Which Operating System causes the issue?

Linux

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.10

### Installed packages

Package                       Version
----------------------------- --------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
ansys-dpf-core                0.12.1
ansys-mapdl-reader            0.51.14
appdirs                       1.4.4
async-timeout                 4.0.2
attrs                         22.1.0
Babel                         2.10.3
cachetools                    5.3.3
certifi                       2024.2.2
charset-normalizer            3.3.2
cycler                        0.11.0
docutils                      0.19
et-xmlfile                    1.1.0
fonttools                     4.34.4
frozenlist                    1.3.1
google-api-core               2.19.0
google-api-python-client      2.131.0
google-auth                   2.29.0
google-auth-httplib2          0.2.0
googleapis-common-protos      1.63.0
grpcio                        1.64.0
httplib2                      0.22.0
idna                          3.7
imageio                       2.21.0
imagesize                     1.4.1
importlib_metadata            7.1.0
Jinja2                        3.1.2
julia                         0.5.7
kiwisolver                    1.4.4
MarkupSafe                    2.1.1
matplotlib                    3.5.2
mpi4py                        3.1.3
multidict                     6.0.2
numpy                         1.24.0
numpydoc                      1.4.0
openpyxl                      3.0.10
packaging                     24.0
pandas                        1.4.3
Pillow                        9.2.0
pip                           22.2.2
port-for                      0.6.2
progressbar2                  4.0.0
proto-plus                    1.23.0
protobuf                      4.25.3
psutil                        5.9.8
pyasn1                        0.6.0
pyasn1_modules                0.4.0
Pygments                      2.12.0
pyparsing                     3.1.2
python-dateutil               2.8.2
python-utils                  3.3.3
pytz                          2022.1
pyvista                       0.36.1
requests                      2.32.2
rsa                           4.9
scipy                         1.9.0
scooby                        0.6.0
setuptools                    70.0.0
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        5.1.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
tqdm                          4.66.4
uritemplate                   4.1.1
urllib3                       2.2.1
vtk                           9.2.0rc2
wslink                        1.6.6
yarl                          1.8.1
zipp                          3.19.0

**Comment by PProfizi** [comment]
Hi @TommasoMarella ,

Are there `AWP_ROOTXXX` environment variables set, or `ANSYS_DPF_PATH`?

**Comment by TommasoMarella** [comment]
Hello,
We have only **AWP_ROOT241=path_to_v241**

**Comment by PProfizi** [comment]
Hi @TommasoMarella,

please try with:
`start_local_server(ansys_path="/net/opt/apps/prod/ansys_2024R1/v241")`

The first positional argument is for the host IP.

**Comment by TommasoMarella** [comment]
Hi @PProfizi ,
with the suggestion now I'm able to start the DPF server, but now we obtained the following error:

Connected to DPF Server: {'server_ip': '', 'server_port': None, 'server_process_id': 65352, 'server_version': '7.1', 'os': 'posix', 'path': '/net/opt/apps/prod/ansys_2024R1/v241/'}

Setting up extraction...
Connection to ansys DPF server closed

Script ended with error:
Traceback (most recent call last):
  File "/net/opt/apps/prod/python/3.10.5-no-static_ansys_2024R1/lib/python3.10/site-packages/ansys/dpf/core/errors.py", line 101, in wrapper
    out = func(*args, **kwargs)
  File "/net/opt/apps/prod/python/3.10.5-no-static_ansys_2024R1/lib/python3.10/site-packages/ansys/dpf/core/model.py", line 353, in time_freq_support
    self._time_freq_support = timeProvider.get_output(0, types.time_freq_support)
  File "/net/opt/apps/prod/python/3.10.5-no-static_ansys_2024R1/lib/python3.10/site-packages/ansys/dpf/core/dpf_operator.py", line 541, in get_output
    internal_obj = type_tuple[1](self, pin)
  File "/net/opt/apps/prod/python/3.10.5-no-static_ansys_2024R1/lib/python3.10/site-packages/ansys/dpf/gate/generated/operator_capi.py", line 599, in operator_getoutput_time_freq_support
    raise errors.DPFServerException(sError.value)
ansys.dpf.gate.errors.DPFServerException: TimeFreqSupportProvider:2<-Data sources not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crackinitiation/src-dev-qa/src/main.py", line 62, in main
    extracted_properties = run_extraction(job, log_fd)
  File "/home/crackinitiation/src-dev-qa/src/main.py", line 109, in run_extraction
    extracted_properties = perform_extraction(job, log_fd)
  File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction_processes_manager.py", line 53, in perform_extraction
    results = perform_extraction_timestep_split(job, log_fd)
  File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction_processes_manager.py", line 219, in perform_extraction_timestep_split
    timesteps_range = check_timesteps_number(job, log_fd) # Remove last timestep (and add warning) if empty and return the list of time steps
  File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction_processes_manager.py", line 545, in check_timesteps_number
    check = ExtractorContainer(job, log_fd)
  File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction.py", line 66, in __init__
    self.__handle_exception(e)
  File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction.py", line 428, in __handle_exception
    raise e
 File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction.py", line 62, in __init__
    self.timesteps, nodes_num = self.__setup()
  File "/home/crackinitiation/src-dev-qa/src/lcf_data_extraction/extraction.py", line 286, in __setup
    tf = self.r.metadata.time_freq_support
  File "/net/opt/apps/prod/python/3.10.5-no-static_ansys_2024R1/lib/python3.10/site-packages/ansys/dpf/core/errors.py", line 106, in wrapper
    raise DPFServerException(details)
ansys.dpf.gate.errors.DPFServerException: TimeFreqSupportProvider:2<-Data sources not defined


Please note, that I used a test case that worked with the previous dpf server (2021R2).

**Comment by ayush-kumar-423** [comment]
Resolved.
cc: @TommasoMarella

**Comment by ayush-kumar-423** [comment]
@PProfizi:

1. Installing Ansys WB 241 and using the DPF Server from the WB installation.
2. Forcing the use of GRPC server:
```
os.environ["DPF_SERVER_TYPE"] = "GRPC"
```
