### ISSUE TITLE
Contact Results are NOT available for CONTA174/Keyopt(4)>2

### ISSUE THREAD

**Issue by GitHubUser120282** [ansys/pydpf-core#1657]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi, 
I read the contact results for certain nodes. It works very well, but if I change the location of contact detection points using Keyopt(4) for CONTA174 to 3 or higher, then no contact results are available (zero entities).

Could you help on this?

### Steps To Reproduce

ID_STEPS=dpf.time_freq_scoping_factory.scoping_on_all_time_freqs(MODEL)
ID_NODES=dpf.Scoping(ids=list(DATA_CONT[:,0].astype(np.int64)),location=dpf.locations.nodal)
RES_CS=dpf.operators.result.contact_status(      data_sources=MODEL,time_scoping=ID_STEPS,mesh_scoping=ID_NODES,bool_rotate_to_global=False).eval()
RES_CP=dpf.operators.result.contact_penetration( data_sources=MODEL,time_scoping=ID_STEPS,mesh_scoping=ID_NODES,bool_rotate_to_global=False).eval()
RES_CG=dpf.operators.result.contact_gap_distance(data_sources=MODEL,time_scoping=ID_STEPS,mesh_scoping=ID_NODES,bool_rotate_to_global=False).eval()

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.12

### Installed packages

Package                  Version
------------------------ --------
ansys-dpf-core           0.10.1
cachetools               5.3.2
certifi                  2024.2.2
charset-normalizer       3.3.2
colorama                 0.4.6
contourpy                1.2.0
cycler                   0.12.1
fonttools                4.49.0
google-api-core          2.17.1
google-api-python-client 2.118.0
google-auth              2.28.0
google-auth-httplib2     0.2.0
googleapis-common-protos 1.62.0
grpcio                   1.60.1
httplib2                 0.22.0
idna                     3.6
importlib-metadata       7.0.1
kiwisolver               1.4.5
matplotlib               3.8.3
numpy                    1.26.4
packaging                23.2
pillow                   10.2.0
pip                      24.0
platformdirs             4.2.0
pooch                    1.8.0
protobuf                 4.25.3
psutil                   5.9.8
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pyparsing                3.1.1
pypdf                    4.0.2
python-dateutil          2.8.2
pyvista                  0.43.3
pywin32                  306
requests                 2.31.0
rsa                      4.9
scipy                    1.12.0
scooby                   0.9.2
setuptools               69.1.0
six                      1.16.0
tqdm                     4.66.2
uritemplate              4.1.1
urllib3                  2.2.1
vtk                      9.3.0
xlwings                  0.30.13
zipp                     3.17.0

**Comment by PProfizi** [comment]
Hello @GitHubUser120282 ,

It turns out this very issue has been solved for DPF 2024 R2. Is it possible for you to change ANSYS version?
If not, you will be able to get this fix by using the `2025.1.pre0` standalone version of DPF starting Thursday July 25.
Here is how you will be able to get it and use it: https://dpf.docs.pyansys.com/version/stable/getting_started/dpf_server.html
