### ISSUE TITLE
DPF for ANSYS 2024R2 requires Python 3.9

### ISSUE THREAD

**Issue by VinodPichamuthu** [ansys/pydpf-core#1885]
### Before submitting the issue

- [x] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

I recently have installed pyansys and ansys-dpf-core python modules to explore and read CFX results file outside ansys environment. But the python script fails as described in the attached image. 

![Image](https://github.com/user-attachments/assets/87fe2e59-d741-4b1c-a7d5-7bdde8d66ff4)
![Image](https://github.com/user-attachments/assets/be490a71-4fce-4300-8d9b-46bd4d5248f8)

### Steps To Reproduce

pip install pyansys and ansys-dpf-core python libraries and execute the below python script

import pyansys
import ansys.dpf.core as dpf

resfilePath = r"[FolderPath]\CFX_001.res"
data_sources = dpf.DataSources()
data_sources.set_result_file_path(resfilePath)
model = dpf.Model(data_sources)
print(model)

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R2

### Which Python version causes the issue?

3.7

### Installed packages

ansys-api-fluent                      0.3.28
ansys-api-mapdl                       0.5.1
ansys-api-meshing-prime               0.1.1
ansys-api-platform-instancemanagement 1.0.0b3
ansys-corba                           0.1.0
ansys-dpf-core                        0.6.0
ansys-dpf-gate                        0.2.1
ansys-dpf-gatebin                     0.4.1
ansys-dpf-post                        0.2.5
ansys-fluent-core                     0.11.0
ansys-grantami-bomanalytics           1.0.1
ansys-grantami-bomanalytics-openapi   1.0.0
ansys-grpc-dpf                        0.8.1
ansys-mapdl-core                      0.63.2
ansys-mapdl-reader                    0.54.1
ansys-meshing-prime                   0.2.0
ansys-openapi-common                  1.1.1
ansys-platform-instancemanagement     1.0.2
ansys-seascape                        0.2.0
appdirs                               1.4.4
cachetools                            5.5.0
certifi                               2024.2.2
cffi                                  1.15.1
chardet                               4.0.0
charset-normalizer                    3.3.2
clr-loader                            0.2.6
colorama                              0.4.6
cryptography                          42.0.5
cycler                                0.11.0
et-xmlfile                            1.1.0
fonttools                             4.38.0
future                                1.0.0
google-api-core                       2.10.1
google-api-python-client              2.151.0
google-auth                           2.35.0
google-auth-httplib2                  0.2.0
googleapis-common-protos              1.56.4
grpcio                                1.62.3
h5py                                  3.8.0
httplib2                              0.22.0
idna                                  2.10
imageio                               2.31.2
importlib-metadata                    4.13.0
keyring                               22.0.1
kiwisolver                            1.4.5
matplotlib                            3.5.3
MIScriptingToolkit                    3.0.16
ntlm-auth                             1.5.0
numpy                                 1.21.6
openpyxl                              3.1.3
packaging                             24.0
pandas                                1.3.5
Pillow                                9.5.0
pip                                   24.0
platformdirs                          4.0.0
plumbum                               1.8.3
pooch                                 1.8.2
protobuf                              3.20.1
protoc-gen-swagger                    0.1.0
psutil                                6.1.0
pyaedt                                0.6.3
pyansys                               2023.1.3
pyasn1                                0.5.1
pyasn1-modules                        0.3.0
pycparser                             2.21
pyiges                                0.3.1
pyparsing                             3.1.4
pypiwin32                             223
python-dateutil                       2.9.0.post0
pythonnet                             3.0.0rc6
pytwin                                0.2.0
pytz                                  2024.1
pyvista                               0.38.6
pywin32                               306
pywin32-ctypes                        0.2.0
requests                              2.31.0
requests-auth                         5.2.0
requests-negotiate-sspi               0.5.2
requests-ntlm                         1.1.0
rescalewrapper                        1.14
rpyc                                  5.0.1
rsa                                   4.9
scipy                                 1.7.3
scooby                                0.7.3
setuptools                            68.0.0
six                                   1.16.0
tqdm                                  4.66.6
typing_extensions                     4.7.1
uritemplate                           4.1.1
urllib3                               1.26.18
vtk                                   9.3.1
wheel                                 0.42.0
zipp                                  3.15.0

**Comment by PProfizi** [comment]
Hi @VinodPichamuthu, to use the right PyDPF libraries for DPF in ANSYS 2024R2, you need at least Python 3.9. If you install ansys-dpf-core the, you should get the latest, or at least `0.12.1` as shown in the compatibility table [here](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html).

**Comment by VinodPichamuthu** [comment]
> Hi [@VinodPichamuthu](https://github.com/VinodPichamuthu), to use the right PyDPF libraries for DPF in ANSYS 2024R2, you need at least Python 3.9. If you install `ansys-dpf-core` then, you should get the latest, or at least `0.12.1` as shown in the compatibility table [here](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html).

Hi @PProfizi, Thanks for your suggestion to upgrade the Python version to 3.9. I am able to read the result files now.

**Comment by VinodPichamuthu** [comment]
@PProfizi , Could you help me to explore some more features similar to what we do in CFX-Post.

For example: Create a Coordinate frame, User surface, export HTC, Tbulk Parameters etc.,
