### ISSUE TITLE
Button for Operator doc not showing

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-core#1900]
### Description of the modifications

We went from this:
![Image](https://github.com/user-attachments/assets/d1d5d4d2-163f-4516-968e-79961c962c59)
To this:
![Image](https://github.com/user-attachments/assets/417c7b1a-86f3-431e-8207-6edbd27c6bc4)

The `OPEN` button disappeared for some reason, which has been reported as problematic since people are used to clicking on it.

### Useful links and references

https://github.com/ansys/pydpf-core/blob/aeca118623f414ab21c5903ae0648664f0774312/doc/source/operator_reference.rst?plain=1#L28

**Comment by PProfizi** [comment]
Hi @Revathyvenugopal162 we had this behavior change with the an update of the `ansys-sphinx-theme`, any idea why?

**Comment by Revathyvenugopal162** [comment]
> Hi [@Revathyvenugopal162](https://github.com/Revathyvenugopal162) we had this behavior change with an update of the `ansys-sphinx-theme`, any idea why?

Yes, it is because of some styles in the custom css, we can fix that by adding some styles or since the card is clickable we can remove that button also. let me know which one you prefer. I will add that in a PR

**Comment by PProfizi** [comment]
Thanks @Revathyvenugopal162 , yes I think users would prefer the button to appear again.

**Comment by Revathyvenugopal162** [comment]
> Thanks [@Revathyvenugopal162](https://github.com/Revathyvenugopal162) , yes I think users would prefer the button to appear again.

sure, i will add that
