### ISSUE TITLE
Edges display does not work correctly

### ISSUE THREAD

**Issue by janvonrickenbach** [ansys/pydpf-core#765]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Showing the mesh of the rst files shows some missing edges and divides 4 node elements into triangles (only thin lines):

![image](https://user-images.githubusercontent.com/7096387/214307218-db3b3c2a-a97c-4b9e-abe7-451f96586378.png)

Here is how the mesh should look like:

![image](https://user-images.githubusercontent.com/7096387/214306944-f2707e20-7a3d-4898-b5fb-3a4c707cb732.png)

This is a simplified model, but the problem occurs for all models that are reasonably complex. In the example below with a few exceptions, all the elements should have only 4 nodes:

![image](https://user-images.githubusercontent.com/7096387/214307716-de8209ee-aec5-4b00-9485-9dde66d83498.png)

Notes: 
- The problem occurs irrespective the pyvista backend and whether the example is run in a notebook or a standalone python script
- It looks like a basic pyvista example already shows some (very) weak lines which divide the quads into triangles: 
![image](https://user-images.githubusercontent.com/7096387/214308603-427a151c-ae50-4345-86b9-d48cf58ecf8c.png)
- The model.metadata.meshed_region.grid object has the right number of quads vs triangles.

### Steps To Reproduce

```
import ansys.dpf.core as dpf

# Remove txt ending of file below and use it to create the model
model = dpf.Model(rst_path)

model.metadata.meshed_region.plot()
```

[file.rst.txt](https://github.com/pyansys/pydpf-core/files/10490465/file.rst.txt)

### Which Operating System are you using?

Windows

### Which DPF/Ansys version are you using?

Ansys 2023 R1

### Which Python version are you using?

3.10

### Installed packages

ansys-dpf-composites     0.1.dev0   
ansys-dpf-core           0.7.2      
ansys-dpf-gate           0.3.0      
ansys-dpf-gatebin        0.3.0      
ansys-grpc-dpf           0.7.0      
anyio                    3.6.2      
appdirs                  1.4.4      
argon2-cffi              21.3.0     
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.2.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
cachetools               5.2.1
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       3.0.1
colorama                 0.4.6
comm                     0.1.2
contourpy                1.0.7
cycler                   0.11.0
debugpy                  1.6.5
decorator                5.1.1
defusedxml               0.7.1
entrypoints              0.4
executing                1.2.0
fastjsonschema           2.16.2
fonttools                4.38.0
fqdn                     1.5.1
google-api-core          2.11.0
google-api-python-client 2.73.0
google-auth              2.16.0
google-auth-httplib2     0.1.0
googleapis-common-protos 1.58.0
grpcio                   1.51.1
httplib2                 0.21.0
idna                     3.4
imageio                  2.24.0
ipykernel                6.20.2
ipython                  8.8.0
ipython-genutils         0.2.0
ipywidgets               8.0.4
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           7.4.9
jupyter-console          6.4.4
jupyter_core             5.1.3
jupyter-events           0.6.3
jupyter_server           2.1.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.5
kiwisolver               1.4.4
MarkupSafe               2.1.2
matplotlib               3.6.3
matplotlib-inline        0.1.6
mistune                  2.0.4
nbclassic                0.4.8
nbclient                 0.7.2
nbconvert                7.2.8
nbformat                 5.7.3
nest-asyncio             1.5.6
notebook                 6.5.2
notebook_shim            0.2.2
numpy                    1.23.5
packaging                23.0
pandocfilters            1.5.0
parso                    0.8.3
pickleshare              0.7.5
Pillow                   9.4.0
pip                      22.2.1
platformdirs             2.6.2
prometheus-client        0.15.0
prompt-toolkit           3.0.36
protobuf                 4.21.12
psutil                   5.9.4
pure-eval                0.2.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
Pygments                 2.14.0
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-json-logger       2.0.4
pyvista                  0.36.1
pywin32                  305
pywinpty                 2.0.10
PyYAML                   6.0
pyzmq                    25.0.0
qtconsole                5.4.0
QtPy                     2.3.0
requests                 2.28.2
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rsa                      4.9
scooby                   0.7.0
Send2Trash               1.8.0
setuptools               63.2.0
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.3.2.post1
stack-data               0.6.2
terminado                0.17.1
tinycss2                 1.2.1
tornado                  6.2
tqdm                     4.64.1
traitlets                5.8.1
uri-template             1.2.0
uritemplate              4.1.1
urllib3                  1.26.14
vtk                      9.2.5
wcwidth                  0.2.6
webcolors                1.12
webencodings             0.5.1
websocket-client         1.4.2
widgetsnbextension       4.0.5

**Comment by PProfizi** [comment]
Hey @AlejandroFernandezLuces, do you think you could take a look at this issue and give your opinion? It might very well be a problem with PyDPF, but I would like to know if there are any chances this comes from PyVista.

**Comment by AlejandroFernandezLuces** [comment]
Sure! I'll take a look as soon as I can.

**Comment by AlejandroFernandezLuces** [comment]
I've been looking into this issue, here's what I've found:
- The triangle division that I see in you images does not appear in my environment. I see that you are using PyVista 0.36, if it's possible consider updating to the latest version, 0.38.1
- Regarding the missing edges, they are not missing really, but they are so thinly rendered that they are not visible. For computing purposes the faces should be fine from pyvista side.

Probably there is a rendering issue in PyVista for the edges with quadratic cells, I also observed that the line width is not consistent for the quadratic cells. 


Here you can see the wireframe representation of the mesh. Here you can see that everything looks fine:
![dpf-wireframe](https://user-images.githubusercontent.com/17165476/216971759-b2a445ba-29d9-490b-a537-ab31f9b72876.PNG)

If you add thickness to the edges, you can see that those edges are not missing, just very thin:
![dps-engrossed2](https://user-images.githubusercontent.com/17165476/216971792-47270575-67fd-4dd4-9805-3d595e807bbf.PNG)

**Comment by janvonrickenbach** [comment]
@AlejandroFernandezLuces : Thanks for looking into the issue. I upgraded to 0.38.1 and see no difference. Which environment are you using? I tried in the notebook and with a standalone python script and I see the same behaviour. I also forced the elements to be linear and don't see a difference. Is there a way to draw all the lines the same thickness and color? Here I'm really interested in a nice looking plot that is comparable to something I would see in an Mechanical or ACP.

**Comment by akaszynski** [comment]
@banesullivan, please prioritize.

**Comment by banesullivan** [comment]
@janvonrickenbach, would you please also share a PyVista Report to help me understand your hardware configuration?:

```py
import pyvista as pv
print(pv.Report())
```

**Comment by banesullivan** [comment]
@AlejandroFernandezLuces, @akaszynski, et al., I'm struggling to get this up and running... would someone be able to save the mesh that's being passed to PyVista and share that with me? `.save('mesh.vtk')`

**Comment by janvonrickenbach** [comment]
> @janvonrickenbach, would you please also share a PyVista Report to help me understand your hardware configuration?:
> 
> ```python
> import pyvista as pv
> print(pv.Report())
> ```

--------------------------------------------------------------------------------
  Date: Fri Mar 31 09:22:03 2023 W. Europe Daylight Time

                OS : Windows
            CPU(s) : 24
           Machine : AMD64
      Architecture : 64bit
               RAM : 63.7 GiB
       Environment : Jupyter
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 770
       GPU Version : 4.5.0 - Build 31.0.101.3358

  Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64
  bit (AMD64)]

           pyvista : 0.38.5
               vtk : 9.2.6
             numpy : 1.23.5
           imageio : 2.27.0
            scooby : 0.7.1
             pooch : v1.7.0
        matplotlib : 3.7.1
           IPython : 8.11.0
        ipywidgets : 8.0.6
              tqdm : 4.65.0
      nest_asyncio : 1.5.6
--------------------------------------------------------------------------------

**Comment by janvonrickenbach** [comment]
@banesullivan: here is the mesh exported in vtk format (Remove the txt ending)
[mesh.vtk.txt](https://github.com/pyansys/pydpf-core/files/11119377/mesh.vtk.txt)

**Comment by janvonrickenbach** [comment]
It looks like it is also looks bad in paraview: 
![image](https://user-images.githubusercontent.com/7096387/229054955-ae677553-32df-4042-84b9-5459bb7680b6.png)

**Comment by banesullivan** [comment]
@janvonrickenbach, thanks for sharing the PyVista Report and the VTK mesh -- I suspect this is a GPU and GL implementation-specific issue. I'll look into this and see what I can uncover.

As a first step, on my M2 Mac with ParaView, I also see some edge rendering issues (some edges aren't visible and many are badly aliased):

![Screen Shot 2023-03-31 at 9 01 34 AM](https://user-images.githubusercontent.com/22067021/229157477-ab21b181-8412-43af-b375-6a8d075c9e9e.png)

I will look into improving this and what exactly is going awry

**Comment by banesullivan** [comment]
I've reported this upstream as it seems to be independent of the graphics hardware and is occurring in both pure VTK and ParaView: https://gitlab.kitware.com/vtk/vtk/-/issues/18866

**Comment by banesullivan** [comment]
It looks to me (without running) that this may be the culprit:

https://github.com/pyansys/pydpf-core/blob/7b5e4826b29e2db4e7a7ff9dc7ed3a40810eed0b/src/ansys/dpf/core/vtk_helper.py#L257-L260

**Comment by janvonrickenbach** [comment]
@PProfizi : It looks like @banesullivan found an issue in the vtk_helper of dpf core. Could you have a look or forward this to the right person?

@banesullivan: Thanks for looking into this.

**Comment by PProfizi** [comment]
Hi @janvonrickenbach, hi @banesullivan,
I'll looking into this
FYI these changes were made in this commit, apparently due to an issue with display of quadsurf elements around January 2021 https://github.com/pyansys/pydpf-core/commit/057da4d8f4bcf9f076a4a8813497fd2506158d9f

**Comment by PProfizi** [comment]
@banesullivan I think it was added to be able to show quadratic elements without internal edges.
I found this releated issue for PyVista, do you have any news regarding this feature request?
https://github.com/pyvista/pyvista/issues/867

**Comment by janvonrickenbach** [comment]
@rafacanton  The result file for the polygon model:
[polygon.rst.txt](https://github.com/pyansys/pydpf-core/files/11308409/polygon.rst.txt)

**Comment by banesullivan** [comment]
@PProfizi, no news at this time -- I gut tells me pyvista/pyvista#867 is unrelated to the issue here

**Comment by janvonrickenbach** [comment]
Thanks for looking into this. I can reproduce that the polygon case looks now much better. However the a bit more complex kiteboard case still looks quite wrong. 

Here is the corresponding rst file:
[file.7z.txt](https://github.com/pyansys/pydpf-core/files/11428857/file.7z.txt)

Output in DPF:
![image](https://user-images.githubusercontent.com/7096387/237036384-4dedf554-783f-4f97-9c5a-666265fa9028.png)


Reference Output in Mechanical:
![image](https://user-images.githubusercontent.com/7096387/237036532-1a910acd-0b43-487a-a085-c777d66448d9.png)

**Comment by rafacanton** [comment]
@janvonrickenbach Thanks for updating this. I've taken a look and at this point it seems like a VTK issue, similar to what was identified in #741. I've noticed that the mesh of the kiteboard example is comprised by a shell plus a point. If I employ the `split_mesh` operator to just have the shell part, I get a correct render:

```
from ansys.dpf import core as dpf

ds = dpf.DataSources(r"D:\kiteboard\file.rst")

mesh = dpf.operators.mesh.mesh_provider(data_sources = ds).eval()

print(mesh)

op = dpf.operators.mesh.split_mesh()
op.inputs.mesh.connect(mesh)
op.inputs.property.connect("elshape")
my_meshes = op.outputs.meshes()

print(my_meshes[0])
print(my_meshes[1])

my_meshes[0].plot()
```

Produces the following (as you can see, the difference between the 2 meshes is just the point element):

```
DPF  Meshed Region: 
  5191 nodes 
  5291 elements 
  Unit: m 
  With shell (2D) elements, shell (3D) elements
DPF  Meshed Region: 
  5189 nodes 
  5290 elements 
  Unit: m 
  With shell (2D) elements, shell (3D) elements
DPF  Meshed Region: 
  1 nodes 
  1 elements 
  Unit: m 
  With 
```

![image](https://user-images.githubusercontent.com/107186344/237043082-8aa3af0d-9871-4619-8138-030674077daf.png)

**Comment by janvonrickenbach** [comment]
@rafacanton Do you expect that any improvements for this problem are implemented in the near future. Otherwise we could also think about a workaround like splitting the mesh before plotting. Is that something that works on a generic model?

**Comment by rafacanton** [comment]
@janvonrickenbach That depends on VTK. @banesullivan, do you think that the underlying issue to this will be fixed soon? (I suspect it is related to this issue from pyvista https://github.com/pyvista/pyvista/issues/4328 and this other one from vtk: https://gitlab.kitware.com/vtk/vtk/-/issues/18958).

Regarding the split of the mesh before plotting, what if all `elshapes` are relevant? For example, take a look at this [example](https://dpf.docs.pyansys.com/version/stable/examples/00-basic/09-results_over_space_subset.html#sphx-glr-examples-00-basic-09-results-over-space-subset-py). It has a mesh with solids, shells and beams, and all of them are relevant. Splitting the mesh and just plotting the solids (for example) wouldn't be useful. Plus, splitting the mesh is a costly operation, so I'm afraid of doing it by default...

**Comment by MaxJPRey** [comment]
Adding @AlejandroFernandezLuces and @RobPasMue for visibility.

**Comment by banesullivan** [comment]
> That depends on VTK. @banesullivan, do you think that the underlying issue to this will be fixed soon? (I suspect it is related to this issue from pyvista https://github.com/pyvista/pyvista/issues/4328 and this other one from vtk: https://gitlab.kitware.com/vtk/vtk/-/issues/18958).

We are actively working on this specific issue in VTK and hope to have an update soon

**Comment by banesullivan** [comment]
I have some news!

https://gitlab.kitware.com/vtk/vtk/-/issues/18958 is fixed upstream, however, it does not impact the issue presented here. 

The issue here was tracked in https://gitlab.kitware.com/vtk/vtk/-/issues/18866 and is specifically when certain edges of a cell are not visible:

![Screen_Shot_2023-04-05_at_9 48 45_AM](https://github.com/ansys/pydpf-core/assets/22067021/3de3c1a3-c7ec-4469-9e51-70c088a63502)

We did a bit of exploration in this thread https://gitlab.kitware.com/vtk/vtk/-/issues/18866#note_1347606 and found that each of these QUAD cells have 8 points where the point IDs are wrapping back on themselves. According to the VTK data model, **a quad must have 4 points**. If it's a higher-order quad, that's permissible. However, they cannot have the same indices as the other points like they do for this mesh.

So this means that the mesh is malformed. Or better yet, that the code producing these meshes is incorrect. I pointed this out above: https://github.com/ansys/pydpf-core/issues/765#issuecomment-1498007751


So the linked code block (or likely something around it) is going to have to change to prevent duplicate point IDs and produce meshes that adhere to the data model.

https://github.com/ansys/pydpf-core/blob/7b5e4826b29e2db4e7a7ff9dc7ed3a40810eed0b/src/ansys/dpf/core/vtk_helper.py#L257-L260

**Comment by janvonrickenbach** [comment]
@banesullivan: Thanks for looking into this. I believe the issue with the malformed mesh has already been fixed in dpf: https://github.com/ansys/pydpf-core/pull/915 (@rafacanton can you confirm this?). So maybe it is just a matter of combining the most recent dev versions of dpf-core and pyvista. If there is a easy way to install a pyvista dev version I can do the testing.

**Comment by rafacanton** [comment]
@banesullivan @janvonrickenbach Correct, the issue of duplicating the node ids is no longer present in dpf. Thanks!

**Comment by banesullivan** [comment]
The version of PyVista shouldn't affect this. Not even the version of VTK. (as long as both are somewhat recent)

**Comment by janvonrickenbach** [comment]
@banesullivan Maybe I misunderstood you, but I wanted to test if a combination of the dpf fix ( #915 ) and the fix in vtk 
 (https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10269 ) fixes the issue. If I understand correctly you tested with a dpf version that did not include #915 .  So I wanted to test with a dev version of vtk that includes https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10269 . Is it easily possible to install such a dev version of vtk?

**Comment by banesullivan** [comment]
> Is it easily possible to install such a dev version of vtk?

There are weekly wheels posted to https://gitlab.kitware.com/vtk/vtk/-/packages

```
pip install vtk --pre --index-url https://gitlab.kitware.com/api/v4/projects/13/packages/pypi/simple
```

**Comment by janvonrickenbach** [comment]
@banesullivan Thanks. With the dev version of vtk and dpf the plot looks finally as expected.
![image](https://github.com/ansys/pydpf-core/assets/7096387/4767382e-51da-4c5f-9bec-0b495d229199)

Thanks to everyone involved. @rafacanton @PProfizi @AlejandroFernandezLuces

**Comment by rafacanton** [comment]
@janvonrickenbach Great news, thanks a lot!
