### ISSUE TITLE
cms_matrices_provider return matrices with wrong shape

### ISSUE THREAD

**Issue by SheBeLo** [ansys/pydpf-core#81]
I've tried the following code:

```python
f_sub = r'C:\path\to\file.sub'

ds  = dpf.DataSources(f_sub) 
sub = dpf.Operator('cms_matrices_provider')  # operator instantiation
sub.inputs.data_sources.connect(ds)
sub_fields = sub.outputs.fields_container()
for field in sub_fields : print(field)
```

The first two fields seems to be stiffness and mass matrices, but associated data have the shape (1, nb_dof²).
Il order to be consistent with others fields, these two matrices should be square and have the shape (nb_dof, nb_dof)

**Comment by rlagha** [comment]
@SheBeLo yes this is a good point, I'll fix this

**Comment by PProfizi** [comment]
Hi @SheBeLo, hi @rlagha,

It is true that the `Field.shape` property reports `(1, nb_dof²)`, but the `Field.dimensionality` does report `(nb_dof, nb_dof)`.

For example, a Field representing matrix data of `[18, 18]` for one entity will store its data in `Field.data` as a numpy array of shape (1, 324).

For two entities, the `Field.data` would be a numpy array of shape (2, 324).

So, the `Field.shape` will report the shape of the numpy array storing data for the entire field, which will be `(nb_entities, nb_dof²)`, whereas `Field.dimensionality` will report the "shape" of the matrix data per entity.

I hope this makes things a bit clearer.

Do not hesitate to reopen this issue if you need more information.
