### ISSUE TITLE
GLEW could not be initialized: Missing GL version

### ISSUE THREAD

**Issue by kanthadya** [ansys/pydpf-core#940]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

data extraction seems to be working fine. The error occurs during plotting

ERROR:root:failed to get wglChoosePixelFormatARB
ERROR:root:failed to get valid pixel format.
ERROR:root:GLEW could not be initialized: Missing GL version

Seems to be a vtk issue. Tried updating vtk from this link as suggested by Alex K but the issue persists

https://discourse.vtk.org/t/status-update-vtk-python-wheels/11212

### Steps To Reproduce

model = dpf.Model(r'C:\Users\sadya\Documents\DROP_TEST\DROP.d3plot')
print(model)
tf = model.metadata.time_freq_support
meshOp = dpf.operators.mesh.meshes_provider()
meshOp.inputs.data_sources.connect(ds)
meshOp.connect(25,[17])
meshes = meshOp.outputs.meshes()

mesh = meshes.get_mesh({'time':3})
print(mesh)
dispP = dpf.operators.result.displacement()
dispP.inputs.data_sources.connect(ds)
dispP.inputs.time_scoping.connect(range(len(tf.time_frequencies.data)))
dispP.connect(25, dpf.Scoping(ids=[17], location="zone"))
disp_field = dispP.outputs.fields_container()
field = disp_field.get_field({'time':3})
model.metadata.meshed_region.plot(field)

### Which Operating System are you using?

Windows

### Which DPF/Ansys version are you using?

DPF Server as standalone

### Which Python version are you using?

3.7

### Installed packages

Package                      Version   Editable project location
---------------------------- --------- --------------------------------------------------------------
ansys-dpf-core               0.8.1
ansys-dpf-gate               0.3.1
ansys-dpf-gatebin            0.3.1
ansys-dpf-server-2023-2-pre2 2023.2rc2 c:\users\sadya\documents\pyd39\dpf_standalone_win_v2023.2.pre2
ansys-dpf-server-2024-1-pre0 2024.1rc0 c:\users\sadya\documents\pyd39\dpf_standalone_win_v2024.1.pre0
ansys-grpc-dpf               0.7.1
anyio                        3.6.2
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
arrow                        1.2.3
asttokens                    2.2.1
attrs                        23.1.0
backcall                     0.2.0
beautifulsoup4               4.12.2
bleach                       6.0.0
cachetools                   5.3.0
certifi                      2022.12.7
cffi                         1.15.1
charset-normalizer           3.1.0
colorama                     0.4.6
comm                         0.1.3
contourpy                    1.0.7
cycler                       0.11.0
debugpy                      1.6.7
decorator                    5.1.1
defusedxml                   0.7.1
executing                    1.2.0
fastjsonschema               2.16.3
fonttools                    4.39.3
fqdn                         1.5.1
google-api-core              2.11.0
google-api-python-client     2.86.0
google-auth                  2.17.3
google-auth-httplib2         0.1.0
googleapis-common-protos     1.59.0
grpcio                       1.54.0
httplib2                     0.22.0
idna                         3.4
imageio                      2.28.1
importlib-metadata           6.6.0
importlib-resources          5.12.0
ipykernel                    6.22.0
ipython                      8.13.2
ipython-genutils             0.2.0
ipywidgets                   8.0.6
isoduration                  20.11.0
jedi                         0.18.2
Jinja2                       3.1.2
jsonpointer                  2.3
jsonschema                   4.17.3
jupyter_client               8.2.0
jupyter_core                 5.3.0
jupyter-events               0.6.3
jupyter_server               2.5.0
jupyter_server_terminals     0.4.4
jupyterlab-pygments          0.2.2
jupyterlab-widgets           3.0.7
kiwisolver                   1.4.4
MarkupSafe                   2.1.2
matplotlib                   3.7.1
matplotlib-inline            0.1.6
mistune                      2.0.5
nbclassic                    1.0.0
nbclient                     0.7.4
nbconvert                    7.3.1
nbformat                     5.8.0
nest-asyncio                 1.5.6
notebook                     6.5.4
notebook_shim                0.2.3
numpy                        1.24.3
packaging                    23.1
pandocfilters                1.5.0
parso                        0.8.3
pickleshare                  0.7.5
Pillow                       9.5.0
pip                          23.1.2
platformdirs                 3.5.0
pooch                        1.7.0
prometheus-client            0.16.0
prompt-toolkit               3.0.38
protobuf                     4.22.4
psutil                       5.9.5
pure-eval                    0.2.2
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
Pygments                     2.15.1
pyparsing                    3.0.9
pyrsistent                   0.19.3
python-dateutil              2.8.2
python-json-logger           2.0.7
pyvista                      0.38.6
pywin32                      306
pywinpty                     2.0.10
PyYAML                       6.0
pyzmq                        25.0.2
requests                     2.30.0
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rsa                          4.9
scooby                       0.7.2
Send2Trash                   1.8.2
setuptools                   65.5.0
six                          1.16.0
sniffio                      1.3.0
soupsieve                    2.4.1
stack-data                   0.6.2
terminado                    0.17.1
tinycss2                     1.2.1
tornado                      6.3.1
tqdm                         4.65.0
traitlets                    5.9.0
typing_extensions            4.5.0
uri-template                 1.2.0
uritemplate                  4.1.1
urllib3                      2.0.2
vtk                          9.2.6
wcwidth                      0.2.6
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.5.1
wheel                        0.40.0
widgetsnbextension           4.0.7
zipp                         3.15.0

**Comment by PProfizi** [comment]
Hi @kanthadya, 
from what I have read online, it seems this could be due to the current driver on your machine. Would it be possible to update it, or at least to check whether it is compatible with OpenGL?

**Comment by PProfizi** [comment]
Closing as stale, please reopen if still relevant
