### ISSUE TITLE
Why model.metadata.available_named_selections is empty with named selections defined in workbench?

### ISSUE THREAD

**Issue by itanfeng** [ansys/pydpf-core#952]
Why model.metadata.available_named_selections is empty? I defined 10 named selections in workbench. I tried to read them from `file.rth` or `file.rst`. The following is the code snippet.

`file = '*/dp0/SYS/MECH/file.rth'   # file.rst`
`model = dpf.Model(file)`
`print(model.metadata.available_named_selections)`

**Comment by itanfeng** [comment]
Hi @PProfizi , Thanks for your help! I have resolved my problem following your advice.
It's my Ansys version problem. My `file.rst` is created in an older version Ansys. The named selections are not stored in `file.rst`.  I rerun the simulation in the current `2023R1` version Ansys. And finally, I can print the named selections.
Thank you very much!

**Comment by PProfizi** [comment]
Hi @itanfeng,
glad you could resolve the issue!
I will close this Issue as resolved, but do not hesitate if you have any other question.
