### ISSUE TITLE
Crash in min_max_over_time_by_entity

### ISSUE THREAD

**Issue by janvonrickenbach** [ansys/pydpf-core#967]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Connect to a dpf server and run the code below. It crashes on the last line. I tried with a server in a docker container as well as the server from the current installer (24R1). Other min_max operators with the same input data work without problems (e.g. min_max_over_label_fc)
```
    test_field = dpf.Field(nature=natures.scalar)
    test_field.append([1.], 1)
    test_field.append([5.], 2)
    test_field.append([3.], 3)

    test_field2 = dpf.Field(nature=natures.scalar)
    test_field2.append([0.], 1)
    test_field2.append([5.], 2)
    test_field2.append([6.], 3)

    fields_container = dpf.FieldsContainer()
    fields_container.add_label("time")
    fields_container.add_field({"time": 1}, test_field)
    fields_container.add_field({"time": 2}, test_field2)

    max_op = dpf.operators.min_max.min_max_over_time_by_entity()
    max_op.inputs.fields_container.connect(fields_container)
    max = max_op.outputs.max()
```

### Steps To Reproduce

See description

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

DPF Server 2023.2.pre1

### Which Python version causes the issue?

3.10

### Installed packages

accessible-pygments           0.0.4
alabaster                     0.7.13
ansys-dpf-composites          0.2.dev0  D:\ANSYSDev\pydpf-composites
ansys-dpf-core                0.8.1
ansys-dpf-gate                0.3.1
ansys-dpf-gatebin             0.3.1
ansys-grpc-dpf                0.7.1
ansys-sphinx-theme            0.9.8                                 
anyio                         3.6.2                                 
appdirs                       1.4.4                                 
argon2-cffi                   21.3.0                                
argon2-cffi-bindings          21.2.0                                
arrow                         1.2.3                                 
astroid                       2.11.7                                
asttokens                     2.2.1                                 
async-lru                     2.0.2                                 
attrs                         23.1.0                                
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.12.2
bleach                        6.0.0
build                         0.8.0
cachetools                    5.3.0
certifi                       2022.12.7
cffi                          1.15.1
cfgv                          3.3.1
charset-normalizer            3.1.0
colorama                      0.4.6
comm                          0.1.3
coverage                      7.2.3
cycler                        0.11.0
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
dill                          0.3.6
distlib                       0.3.6
docutils                      0.19
exceptiongroup                1.1.1
executing                     1.2.0
fastjsonschema                2.17.1
filelock                      3.11.0
fonttools                     4.38.0
fqdn                          1.5.1
google-api-core               2.11.0
google-api-python-client      2.84.0
google-auth                   2.17.2
google-auth-httplib2          0.1.0
googleapis-common-protos      1.59.0
grpcio                        1.53.0
httplib2                      0.22.0
identify                      2.5.22
idna                          3.4
imageio                       2.27.0
imagesize                     1.4.1
importlib-metadata            4.13.0
iniconfig                     2.0.0
ipykernel                     6.23.1
ipython                       8.13.2
isoduration                   20.11.0
isort                         5.11.5
jaraco.classes                3.2.3
jedi                          0.18.2
Jinja2                        3.1.2
json5                         0.9.14
jsonpointer                   2.3
jsonschema                    4.17.3
jupyter_client                8.2.0
jupyter_core                  5.3.0
jupyter-events                0.6.3
jupyter-lsp                   2.1.0
jupyter_server                2.5.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.0
jupyterlab-pygments           0.2.2
jupyterlab_server             2.22.1
keyring                       23.13.1
kiwisolver                    1.4.4
lazy-object-proxy             1.9.0
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib                    3.5.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       2.0.5
more-itertools                9.1.0
mypy                          1.2.0
mypy-extensions               1.0.0
nbclient                      0.8.0
nbconvert                     7.4.0
nbformat                      5.8.0
nest-asyncio                  1.5.6
nodeenv                       1.7.0
notebook_shim                 0.2.3
numpy                         1.24.3
numpydoc                      1.5.0
packaging                     23.0
pandocfilters                 1.5.0
parso                         0.8.3
pep517                        0.13.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.0.1
pkginfo                       1.9.6
platformdirs                  3.2.0
pluggy                        1.0.0
pre-commit                    3.3.1
prometheus-client             0.17.0
prompt-toolkit                3.0.38
protobuf                      4.22.1
psutil                        5.9.4
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.21
pydata-sphinx-theme           0.13.3
Pygments                      2.15.0
pylint                        2.13.9
pypandoc                      1.11
pyparsing                     3.0.9
pyrsistent                    0.19.3
pytest                        7.3.1
pytest-cov                    3.0.0
python-dateutil               2.8.2
python-json-logger            2.0.7
pyvista                       0.36.1
pywin32                       306
pywin32-ctypes                0.2.0
pywinpty                      2.0.10
PyYAML                        6.0
pyzmq                         25.0.2
readme-renderer               37.3
requests                      2.28.2
requests-toolbelt             0.10.1
rfc3339-validator             0.1.4
rfc3986                       2.0.0
rfc3986-validator             0.1.1
rich                          13.3.3
rsa                           4.9
scipy                         1.9.3
scooby                        0.7.1
Send2Trash                    1.8.2
setuptools                    67.6.1
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
soupsieve                     2.4
Sphinx                        5.3.0
sphinx_autodoc_typehints      1.20.1
sphinx-copybutton             0.4.0
sphinx_design                 0.3.0
sphinx-gallery                0.11.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
terminado                     0.17.1
tinycss2                      1.2.1
tomli                         2.0.1
tornado                       6.3.2
tqdm                          4.65.0
traitlets                     5.9.0
twine                         4.0.2
typing_extensions             4.5.0
uri-template                  1.2.0
uritemplate                   4.1.1
urllib3                       1.26.15
virtualenv                    20.21.0
vtk                           9.2.6
wcwidth                       0.2.6
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.5.2
wheel                         0.40.0
wrapt                         1.15.0
zipp                          3.15.0

**Comment by PProfizi** [comment]
Hi @janvonrickenbach,
I was able to get a crash in the same conditions as you provided:
`line 384, in operator_getoutput_fields_container
    res = capi.dll.Operator_getoutput_FieldsContainer(op._internal_obj if op is not None else None, utils.to_int32(iOutput), ctypes.byref(utils.to_int32(errorSize)), ctypes.byref(sError))
OSError: exception: access violation reading 0x0000000000000020`
Did you get something similar or was that something else?

**Comment by janvonrickenbach** [comment]
> Hi @janvonrickenbach, I was able to get a crash in the same conditions as you provided:
> 
> ```
> line 384, in operator_getoutput_fields_container
> res = capi.dll.Operator_getoutput_FieldsContainer(op._internal_obj if op is not None else None, utils.to_int32(iOutput), ctypes.byref(utils.to_int32(errorSize)), ctypes.byref(sError))
> OSError: exception: access violation reading 0x0000000000000020
> ```
> 
> Did you get something similar or was that something else?

That's exactly what I got. Thanks for reproducing.

**Comment by ansys-akarcher** [comment]
@janvonrickenbach 

You may be able to work with the following piece of code (on current master branch, or what you were using before, no need to get my changes)
```python
from ansys.dpf import core as dpf

test_field = dpf.Field(nature=dpf.natures.scalar)
test_field.append([1.], 1)
test_field.append([5.], 2)
test_field.append([3.], 3)

test_field2 = dpf.Field(nature=dpf.natures.scalar)
test_field2.append([0.], 1)
test_field2.append([5.], 2)
test_field2.append([6.], 3)


#fields_container = dpf.FieldsContainer()
fields_container = dpf.fields_container_factory.over_time_freq_fields_container(
                                                                                fields={
                                                                                    0.1: test_field,
                                                                                    0.2: test_field2
                                                                                    })
max_op = dpf.operators.min_max.min_max_over_time_by_entity()
max_op.inputs.fields_container.connect(fields_container)

max = max_op.outputs.max()

print(max[0].data)
```
Here I modified 1 and 2 by 0.1 and 0.2 as an example.


Sorry for the unusually late answer.

**Comment by janvonrickenbach** [comment]
@ansys-akarcher Thanks for the fix. I'll try if it helps. Actually, the code above was just a preliminary test whether the min_max_over_time_by_entity operator does what I expect it to do. Eventually I will use the operator from C++. I see that you fixed this problem on the python side. Do I have to do something special with the timesupport if I write my C++ code?

**Comment by ansys-akarcher** [comment]
@janvonrickenbach So actually I will abort the python PR as it is a workaround, not a fix.
The issue lies in C++ where this operator expects a TimeFreqSupport to be bound to the FieldsContainer.
I already made the PR in C++ to fix this behavior, I hope it will be merged today, I can keep you up to date.

**Comment by janvonrickenbach** [comment]
@ansys-akarcher Yes please let me know when this is fixed. We consume that standalone package so I should able to test this soon after it is merged.

**Comment by janvonrickenbach** [comment]
Hi @ansys-akarcher I tried to run the example with your fix and I can now successfully get the max output. Also the results are correct. However, if I try to get the time_freq_of_min or time_freq_of_max output, I get the error "result not found": 

![image](https://github.com/ansys/pydpf-core/assets/7096387/cf5f406f-a682-4da4-8ea1-7cbb84b7a8c5)


This is with the server from the daily installer from end of last week and  the python version 0.8.2dev0. Can you reproduce this problem and do you have an idea why it occurs?

**Comment by ansys-akarcher** [comment]
@janvonrickenbach So does your input fields_container has a time_freq_support attached to it ?

If not this is more of a documentation issue (optional outputs), otherwise if you have a time freq support on your fields container, then it's indeed a bug.

**Comment by janvonrickenbach** [comment]
@ansys-akarcher Indeed I did not have time_freq_support. I had a time label, but this is probably not enough.
If try to add the time_freq_support with the following code I get an error:

```
test_field = dpf.Field(nature=natures.scalar)
test_field.append([1.], 1)
test_field.append([5.], 2)
test_field.append([3.], 3)
test_field.unit = "m"
test_field2 = dpf.Field(nature=natures.scalar)
test_field2.append([0.], 1)
test_field2.append([5.], 2)
test_field2.append([6.], 3)
test_field2.unit = "m"

"""
fields_container = dpf.FieldsContainer()
fields_container.add_label("time")
fields_container.add_field({"time": 1}, test_field)
fields_container.add_field({"time": 2}, test_field2)
"""

fields_container = dpf.fields_container_factory.over_time_freq_fields_container(
                                                                                fields={
                                                                                    1: test_field,
                                                                                    2: test_field2
                                                                                    })

max_op = dpf.operators.min_max.min_max_over_time_by_entity()
max_op.inputs.fields_container.connect(fields_container)

max = max_op.outputs.max()
```
![image](https://github.com/ansys/pydpf-core/assets/7096387/71f4e25a-3899-4ce2-9de3-21fd60f1b9f2)

I tried to set the units of the field but it did not help. Any ideas?

**Comment by ansys-akarcher** [comment]
Ok, so one the fix in the PR that I wrote does the job: https://github.com/ansys/pydpf-core/pull/996/files#diff-c32d511649a46713a9f95d5f5eb8a4f5105eac4032a20c801c2ec5ff406dc53cR65

then the time_freq_of_min and time_freq_of_max works as expected.

I will update & complete it

**Comment by janvonrickenbach** [comment]
With the above mentioned fix, this works now as expected.
